### ISSUE TITLE
Using NFS shares

### ISSUE THREAD

**Issue by tiritibambix** [kieraneglin/pinchflat#107]
Hello again.

I was experimenting with Pinchflat and it looks promising.

I have a machine for downloading media and another that serves as a media center.

I'm afraid to try it so I'd better ask: would it technically be possible to mount `/downloads` as an NFS share to download the media directly into my media center or will I have issues ?

**Comment by kieraneglin** [comment]
I don't use it as a networked share, but I have my media center directory structure like this:

```
Streaming Media/
  Shows/
    ...
  Movies/
    ...
  Youtube/
    ...
```

Pinchflat downloads directly to the `Youtube/` directory and in plex I've added that directory as one of the places it searches for TV Shows (as well as `Shows/`, of course). This lets me keep my data separate, but it still shows up in Plex how I want! And if something goes wrong, the data _should_ be isolated. So what I'm saying is that it's worth a shot!

Your mileage may if you're using something other than Plex but the general idea should hold. Also worth checking out [this](https://github.com/kieraneglin/pinchflat/wiki/Frequently-Asked-Questions#how-do-i-get-media-into-plexjellyfinkodi) FAQ entry

**Comment by tiritibambix** [comment]
Thanks a lot for jour feedback.

I'll have a try at it and report back :)

**Comment by reefland** [comment]
It was easy to mount `/downloads` as a NFS share with Pinchflat under Kubernetes to my TrueNAS server.

**Comment by tiritibambix** [comment]
> It was easy to mount `/downloads` as a NFS share with Pinchflat under Kubernetes to my TrueNAS server.

That's great news. Thanks :)
