### ISSUE TITLE
Provide alternate image registry to dockerhub

### ISSUE THREAD

**Issue by onedr0p** [kieraneglin/pinchflat#109]
Hi 👋🏼 Awesome project here...

Dockerhub has aggressive pull rate limits, it would be awesome if you could push the image to Github Container Registry (GHCR) too.

Dockerhub was one of the best years ago... GHCR is completely free for open source projects. It's also nice in that it integrates into your repo under the packages section. Take a look at my project [here](https://github.com/onedr0p/exportarr) and look at the packages on the right side.

Thanks!

**Comment by kieraneglin** [comment]
Damn, looks like I misread things initially. I originally planned to go with GHCR, but when reading [this](https://docs.github.com/en/billing/managing-billing-for-github-packages/about-billing-for-github-packages#about-billing-for-github-packages) I thought the storage limits would be inadequate. I completely missed the very first line which reads `GitHub Packages usage is free for public packages`.

Oh well. Thanks for the callout! I'll put this on the list

**Comment by kieraneglin** [comment]
Done! Once [this actions run](https://github.com/kieraneglin/pinchflat/actions/runs/8412639486) completes, the `latest` will be available on both Docker Hub and GHCR.

Thanks again for the tip!

**Comment by onedr0p** [comment]
This is awesome, thank you so much!
