### ISSUE TITLE
Remove items from "Pending Media"

### ISSUE THREAD

**Issue by ItsNoted** [kieraneglin/pinchflat#111]
I had to reboot my VM in the middle of downloads and it seems to have broken the app. There have been 2 downloads stuck in Pending Media with no way to remove them.

![image](https://github.com/kieraneglin/pinchflat/assets/57927413/f97e431d-987b-4479-92a8-41f7f30528b6)

**Comment by kieraneglin** [comment]
That's good to know! I was wondering what happens in that case. 

Try editing the source two times - once to disable downloading media then again to re-enable it. That should restart the download jobs

**Comment by kieraneglin** [comment]
Ended up being a pretty easy fix! I'm going to get a few more changes put together before releasing this generally, but it should be out by this evening. Tomorrow evening latest.

Thank you for the report!

**Comment by ItsNoted** [comment]
Awesome work thank you!

**Comment by kieraneglin** [comment]
(FYI) The fix will be up once [this actions run](https://github.com/kieraneglin/pinchflat/actions/runs/8412639486) completes (should be ~10 minutes)
