### ISSUE TITLE
Preferred resolution not downloading

### ISSUE THREAD

**Issue by volcs0** [kieraneglin/pinchflat#125]
I have a media profile set up for 4K, but videos are coming down in 480p most of the time. I checked some of these videos in the browser, and they are indeed 4K or 1080.  Not sure which version I'm using (don't see it on the browser page). Using Docker on unRAID.

**Comment by kieraneglin** [comment]
Thanks for the report! would you mind passing along an example channel or playlist that's doing this so I can test it?

**Comment by volcs0** [comment]
I was wrong! My viewer was defaulting to a lot resolution, but I was able to change it. 
Sorry! Can close ticket.
