### ISSUE TITLE
FR: Redownload new videos after delay

### ISSUE THREAD

**Issue by fritolays** [kieraneglin/pinchflat#127]
Hello, really enjoying using pinchflat docker on unraid so far.

Just looking for some more info regarding how the download format is being selected.
From what I understand of download_option_builder.ex, it seems to already favour avc and m4a codecs, which is what I want.
But will an option be added to select the preferred codecs?
Seems your comments may already hint at adding a means for custom arguments.

Second, I am currently using YoutubeDL-Material and it has a feature that will check new uploads a day later to allow for enough processing time of higher qualities.
<img width="169" alt="Screenshot 2024-03-25 225647" src="https://github.com/kieraneglin/pinchflat/assets/855555/548c959e-7cce-4794-9649-ece7e7a27b35">
Could a delay option be added to the media profiles?
So that once a new video is detected it waits X time before fetching it.
Could also be handy if you plan on implementing sponsorblock segment removal in the future.

**Comment by kieraneglin** [comment]
Hey there! Thanks for the report (:

>  will an option be added to select the preferred codecs?

Eventually, but probably not anytime soon. Not because I don't see the value, but because there are a lot of other things to do first and I don't mind being a little prescriptive.

>  Could a delay option be added to the media profiles?

That's a _really_ good idea. I probably won't make it an option (again, being prescriptive) but I'll automatically retry the download one time 24h after upload if it would improve quality. I'll put that on the list!

>  Could also be handy if you plan on implementing sponsorblock segment removal in the future.

That's one of the next things I'll be working on 🤙

**Comment by fritolays** [comment]
Just to add a couple extra pennies...
Exposing the time delay as an advanced setting in the media profile would be nice.
For some of my videos it takes about a week for good sponsorblock segments to be agreed upon.

**Comment by kieraneglin** [comment]
That's a fair point! I've added that to my notes

**Comment by kieraneglin** [comment]
As long as nothing pressing comes up in the next little while, this will be the next feature I'll work on!

**Comment by kieraneglin** [comment]
Done! This will be out in the next release (probably later today or tomorrow)

**Comment by fritolays** [comment]
Seems to work as expected, thanks kindly.
![image](https://github.com/kieraneglin/pinchflat/assets/855555/c5e41ee6-295c-43dd-a711-5b9dffc6b4c1)
