### ISSUE TITLE
FR: Show number of downloaded videos in `Downloaded Media` tab

### ISSUE THREAD

**Issue by W-KE** [kieraneglin/pinchflat#131]
As a user,
I want to see the number of downloaded videos in the `Downloaded Media` tab of each source,
So I can tell if all videos have been downloaded from that source.

For example:
<img width="1473" alt="image" src="https://github.com/kieraneglin/pinchflat/assets/19321302/bdbc969d-7682-4c1a-b93d-f74494d097a1">

**Comment by kieraneglin** [comment]
I dig it! Will do

**Comment by kieraneglin** [comment]
Done! This will be going out in the next release (probably later today)
