### ISSUE TITLE
Source `index_frequency_minutes` value not being updated

### ISSUE THREAD

**Issue by Stolz** [kieraneglin/pinchflat#132]
When you add/edit a source, regardless of what value you select in the `Index Frequency` dropdown menu, the value always gets saved as 43200 ( 30 days). 

Screenshot: https://imgur.com/a/Hch0n6a

**Comment by kieraneglin** [comment]
Hey there!

This is expected - fast indexing overrules index frequency. There is a blurb in the UI  but I have a note to disable that input when fast indexing is enabled
