### ISSUE TITLE
FR:  The ability to import downloaded media and subscriptions from apps like tubesync or  YoutubeDL

### ISSUE THREAD

**Issue by nirav72** [kieraneglin/pinchflat#143]
Until pinchflat came along - I like many others used apps like tubesync or youtubedl-material locally archiving youtube playlists or channels.   Tubesync specifically has similar tasks setup for automatically downloading media from a channel or playlist source. As well managing the media.   Would be really useful if I Pinchflat could import existing task & source directly from tubesync and also directory scanning. (reading nfo and json files, as well as directory name). Similar to how Sonarr can import shows already on a drive.

**Comment by kieraneglin** [comment]
Hey there! Thanks for the report (:

To be honest, I don't think either of these are likely to be added. Pinchflat works by having a strict internal structure for its data and it'd be _very_ difficult to backfill that data from other apps/from JSON files. 

I know it's not ideal, but I don't see a way around it without compromising how the app works. 

Let me know if you have any questions!
