### ISSUE TITLE
FR: Allow setting frame-ancestors header for adding Pinchflat to a dashboard like Organizr

### ISSUE THREAD

**Issue by unixrubix** [kieraneglin/pinchflat#149]
An option either in-app or during Docker config to set the [CSP frame-ancestors](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors) header would allow Pinchflat to be added to a network services organizer dashboard for simplified access. 

Setting the CSP frame-ancestors header should override the current X-Frame-Options header and retain click-jacking security.

I'm only familiar with this from an Nginx approach rather than Elixir, but [this](https://stackoverflow.com/questions/53159267/setting-x-frame-options-in-phoenix-response) seemed like a possible solution.

**Comment by kieraneglin** [comment]
Thanks for the report!

Seems fair enough. Since this is only meant to be self-hosted, I think it's fair game to unset the `x-frame-options` header entirely.

I'll look into that tonight!

**Comment by kieraneglin** [comment]
This is fixed in the latest release!

**Comment by unixrubix** [comment]
Awesome thank you!
