### ISSUE TITLE
Doubts about resource consumption

### ISSUE THREAD

**Issue by somethingGoneWrong** [kieraneglin/pinchflat#151]
Hi, I've been using the program for a few days now and I've noticed intensive CPU and RAM usage, the downward spike at 4:00 AM is due to the automatic update of the docker image.

![screen](https://github.com/kieraneglin/pinchflat/assets/40141099/c1446727-9224-483b-bcd9-9a5a80e2d50e)

maybe I'm putting too many youtube channels to control? Should I put less?

![screen#4](https://github.com/kieraneglin/pinchflat/assets/40141099/8b2949de-d65d-4d15-8722-ef68da28190a)

I see that it goes continuous prompts as if it continuously updates them all, while in the settings I selected daily update.
I'll leave a few more pictures, if needed I can post logs.
Pinchflat has the purple color line:

![screen#2](https://github.com/kieraneglin/pinchflat/assets/40141099/3fde706f-9299-4d6a-93a5-d9c404b8e802)

![screen#3](https://github.com/kieraneglin/pinchflat/assets/40141099/cb493ab5-6acc-4fee-bd82-72ddede0d3a9)

![screen#1](https://github.com/kieraneglin/pinchflat/assets/40141099/fc45082f-ad7f-4c36-bb1d-cfe1286d6579)

**Comment by kieraneglin** [comment]
Thanks for the report!

Would you mind posting this exact message in #130? You should be able to click "edit" on that post and copy+paste that verbatim (:

I've been looking into resource usage re: yt-dlp as part of #130 and it seems like there are some issues in yt-dlp that I'll have to try and work around. 

Anyway, I'll be closing this in favour of #130 so I can keep everything consolidated
