### ISSUE TITLE
Bug: Thumbnails not embedding properly in Emby

### ISSUE THREAD

**Issue by ItsNoted** [kieraneglin/pinchflat#153]
Sometimes the app will only embed a screenshot of the Youtube episode and not the video thumbnail. See the attached image. Sometimes it wont embed an image at all. Graser has thumbs for all his videos so I'm not sure what is going on here. Let me know if you need anything else from me for troubleshooting.

![chrome_RxI83B8ZrF](https://github.com/kieraneglin/pinchflat/assets/57927413/567d6397-510d-4c39-ae90-168febdf0ee4)

![chrome_DNcnugBxsQ](https://github.com/kieraneglin/pinchflat/assets/57927413/2d8da850-6bed-426f-ad57-2e99291d5cc2)

Here are the Pinchlflat options enabled.

![chrome_T8iAD2Uzqb](https://github.com/kieraneglin/pinchflat/assets/57927413/36bcff11-0c46-4638-b942-b474c8c6199f)

**Comment by kieraneglin** [comment]
Hey there! Thanks for the report (:

For troubleshooting, would you mind checking if the media actually has a thumbnail embedded by navigating to it using your computer's file browser? That will help me determine if it's on Emby's side or the app's side

**Comment by ItsNoted** [comment]
You can see here when I browse to the folder some are not displaying a thumbnail.

![explorer_cd2lIVEwQc](https://github.com/kieraneglin/pinchflat/assets/57927413/c4cf9a6e-8c91-4d2d-a25e-296638badea5)

**Comment by kieraneglin** [comment]
I've been struggling to replicate this issue, going as far as downloading that YouTube channel to compare. 

The app doesn't really do anything in terms of embedding thumbnails - it just passes those arguments directly to yt-dlp for it to work with.

Did any of the media profile's settings change while that source was being downloaded? Or is there anything running on your server that could modify the files as they're being downloaded?

**Comment by ItsNoted** [comment]
Hmm. Yeah I'm scratching my head on this one If it were a permission issue why would it do some but not the others? This is the only app running on the container and no settings were changed while downloads were being made.

**Comment by ItsNoted** [comment]
I think it has to do with the tmp folder before moving the files. Is there a way to mount this tmp folder so I can give it permissions inside the docker container?

**Comment by ItsNoted** [comment]
I think I figured it out! I had this option checked in Emby to fetch a screenshot and I think it may have been using it as the thumbnail.

![chrome_RV7ytOOlc6](https://github.com/kieraneglin/pinchflat/assets/57927413/28b67648-6620-4456-b44c-6138929dc31a)

**Comment by kieraneglin** [comment]
That makes sense as a culprit! Also I love the screenshot

Thanks for following up 🤙
