### ISSUE TITLE
Enhancement: Improve tab UI behaviour

### ISSUE THREAD

**Issue by kieraneglin** [kieraneglin/pinchflat#158]
The tabbed UI for sources (and the other models to a lesser extent) need some love. A few items in no order:

- ~Reloading the page should keep you on the same tab~ (added in #161)
- ~Navigating back/forward should respect tab click history~ (added in #161)
- ~Tabs that show records should have pagination to ensure all records can be displayed~ (added in #190)
- ~Tabs that show records should have sensible ordering~
- (Stretch goal) Tabs should live update, if applicable
  - Edit: won't get to live updating now - will create a new ticket if that ever comes around

**Comment by Nairou** [comment]
I'd like to add: Tabs where "newest" isn't important should ideally be ordered by name. For example, the list of sources. I didn't add them in alphabetical order, so now I have to scan the full list to find one.

**Comment by kieraneglin** [comment]
@Nairou that change was made with #164 and will be going out as part of `v0.1.8`. Not sure when that will release but it'll be within the next day or two
