### ISSUE TITLE
[Request] Automatically group videos with related titles

### ISSUE THREAD

**Issue by LoganJFisher** [kieraneglin/pinchflat#175]
For example, the channel OverSimplified has the videos "WW2 - OverSimplified (Part 1)" and "WW2 - OverSimplified (Part 2)". I would like a way to have videos that share the same title except for some indication of being separate parts of an ongoing series (typically something like above or simply a number) to automatically be sorted together into a folder named only the common part of their names minus certain special characters. So in the above case, the folder name would be "WW2 - Oversimplified".

Combined with #174, the folder name would instead just be "WW2".

**Comment by kieraneglin** [comment]
Similar to #174, this is now technically possible but there are support implications!

This is untested, but this may do what you want:

```
--parse-metadata "series:(?P<series>(WW2|WW1)"
```

The output template could be something like ` ... /{{ series }} - {{ channel }}/...`

Then you could use `yt-dlp` [output template syntax](https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#output-template) to provide things like placeholders and default values. But all of that is considered out-of-band of Pinchflat so I'd consider checking out the `yt-dlp` GitHub issues or Discord if you need help crafting that output template 🤙
