### ISSUE TITLE
Pinchflat support for other sites (Twitch, Nebula, etc)

### ISSUE THREAD

**Issue by kieraneglin** [kieraneglin/pinchflat#177]
## Issue Statement

Pinchflat currently does not _officially_ support any site other than YouTube and that isn't likely to change any time soon. That said, `yt-dlp` supports [_many_ sites ](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) and there's a fair chance Pinchflat would work with those sites - especially the most popular ones.

This closed issue will stand as a repository of known issues and workarounds for downloading media from other sites. It's almost certain that Pinchflat won't work 100% as expected with non-YouTube sites BUT if there's an issue that's an easy change and would also be applicable to YouTube, it _may_ get fixed. Just remember that the focus is YouTube first and foremost and it's more like a happy accident if Pinchflat works with other sites.

## Known Limitations

- Fast indexing only works with YouTube - make sure you disable it for any non-YouTube sources
- Some pure-audio sources (like iheartradio) don't download 

## Workarounds

- None known

**Comment by matejdro** [comment]
Just wondering, how does "one-off video" workaround work for other sites? Most of them don't have unlisted playlists, so you can't use the main workaround.

**Comment by warieon** [comment]
Twitch working - can configure your output path as:
/shows/{{ source_custom_name }}/{{ season_by_year__episode_by_date_and_index }} - {{ title }}.{{ ext }}
I also turned off all radio buttons, and set past livestreams to include.

For the sources, I just grabbed the URL from clicking on the Videos button on the streamer's profile.

**Comment by climba03003** [comment]
I have tested for more site, it should be good enough to fetch and download most of the sites that `yt-dlp` support.

I actually rebuilt the image with `yt-dlp_linux`, the current docker image is lacking the support for `websocket` and `curl_cliff`.
You can change the Dockerfile in mentioned line.
https://github.com/kieraneglin/pinchflat/blob/59f8aa69cdbc27625120fe85a236ff2166445562/docker/selfhosted.Dockerfile#L102-L105

**Comment by giantsfan006** [comment]
Figured I'd give it a shot and found that Pornhub doesn't seem to work. Tried both playlists and channels and both threw generic errors in the UI:

`Oops, something went wrong! Please check the errors below.`

Nothing below noted so I checked the logs and only saw this:

`2025-07-21 21:16:54.144 request_id=GFR3vkrMdzCtn4sAMJZC [info] | [command_wrapper]: /usr/local/bin/yt-dlp called with: https://www.pornhub.com/playlist/313166221 --simulate --skip-download --ignore-no-formats-error --playlist-end 1 --print-to-file %(.{channel,channel_id,playlist_id,playlist_title,filename})j /tmp/pinchflat/data/91/65/9165fc0b4050078629f124cf6699fea3d76963883f1f9a534b8ec805e4fd62a6.json --windows-filenames --quiet --cache-dir /tmp/pinchflat/data/yt-dlp-cache`
