### ISSUE TITLE
Bug: Apprise notifications for non-pending media

### ISSUE THREAD

**Issue by Nairou** [kieraneglin/pinchflat#184]
Pinchflat appears to be sending Apprise notifications every 15 minutes, claiming certain sources have new media, but nothing gets downloaded. Manually checking YouTube shows that there is nothing new for those channels.

Is it getting hung up on older videos that shouldn't be downloaded? The notifications become less useful if they only show the possibility of a download.

![image](https://github.com/kieraneglin/pinchflat/assets/942190/2d6909d7-8ee9-434b-84ef-6914b86de373)

**Comment by kieraneglin** [comment]
Thanks for the report!

That's definitely a bug. I'm fighting off a hell of a cold at the moment but I'll look into it when I can 🤙

**Comment by kieraneglin** [comment]
Got it figured! Ended up being a pretty easy fix.

Will be released as part of `v0.1.14` which should come out either later today or tomorrow

**Comment by kieraneglin** [comment]
Just pushed `v0.1.14` which should be good to go in about 15 mins. Thanks again for the report!
