### ISSUE TITLE
Keep track of playlists (for plex)?

### ISSUE THREAD

**Issue by jschwalbe** [kieraneglin/pinchflat#196]
This may already be implemented, but I haven't quite figured it out yet. Love the app so far!

I am working on downloading an entire channel. The channel has various playlists (and sometimes the same video might be on multiple different playlists). Is there a way to keep the playlists 'in tact' on Plex? For example, can I go to "Artist" / Playlists and load "March 2024 workout playlist" which includes videos 1, 2, 3 and 4; and then load "April 2024 playlist" which includes videos 5, 6, 7, and 2?

If I've not made myself clear enough, I can try to elaborate! Thanks again

**Comment by kieraneglin** [comment]
I think I understand what you mean! Unfortunately, this isn't supported by `yt-dlp` (which the app uses under-the-hood) so it's not _automatically_ supported in-app. That said, you can add each playlist as its own Source and add _those_ to a Plex playlist! 

You may also be able to use the `Output path template override` option for a Source to get the file structure setup how you like. If you want to use this feature you have to enabled "advanced" mode - there's a button for this in the upper right of the Source form!

---

I'll close this issue but please let me know if I misunderstood and I'll re-open it!
