### ISSUE TITLE
[FR] Add episode art to podcast feed

### ISSUE THREAD

**Issue by sean89503** [kieraneglin/pinchflat#200]
this is a feature supported by major podcast mangers, episode art it can be added to the item feed 'itunes:image' and formatted  {'href': thumbnail_url})

**Comment by kieraneglin** [comment]
Thanks for the report!

That's fair enough and should be an easy change! I'll add that to the list 🤙

**Comment by kieraneglin** [comment]
This has been solved and will go up in the next release (`v0.1.16`)! I'm not sure when that'll go out but probably sometime early-mid next week.

Heads up that it'll only include episode artwork if the profile is set to download thumbnails. Without a thumbnail it'll fall back to the channel's art

**Comment by kieraneglin** [comment]
@sean89503 The release with this change has been pushed and will be available in ~15 minutes 🤙
