### ISSUE TITLE
Thumbnail file names are incorrect.

### ISSUE THREAD

**Issue by Gex2501** [kieraneglin/pinchflat#203]
When downloading thumbnails, Pinchfalt appends "-thumb" to the file name before the extension. It would be prefereable not to do this, or at least have a way to switch off/cusomize this, as Plex for one simply looks for thumbnails in local media assets being the same name with a different extension. Something like this...
VideoFile.mp4
VideoFile.jpg

**Comment by kieraneglin** [comment]
Hey there, thanks for the report! 

That suffix is required to support other media center apps that don't support embedded metadata. Plex (and I think Jellyfin) should be able to use the embedded thumbnail and metadata in the video file as long as the relevant settings are enabled. I'm out of the house at the moment, but there's a blurb in the FAQ about relevant Plex settings you need to enable (click the `Docs` sidebar button in-app and FAQ should be on the right)

![Screenshot_20240428-211110~2.png](https://github.com/kieraneglin/pinchflat/assets/569917/cb351a52-a30a-441d-861b-a0cb4b3d67c4)

**Comment by Gex2501** [comment]
Yeah, I've been messing with my Plex settings for the better part of the weekend. I can't ever seem to get things to work out consistently. Mainly because I have a lot of playlists I want to download/sync. A playlist in particular can have multiple videos on the same day which makes them see like the same season & episode number. It's been frustrating.

**Comment by Gex2501** [comment]
I'll just close this but I still think a way to configure the "-thumb" extension would be desirable.

**Comment by kieraneglin** [comment]
That may be possible via custom yt-dlp arguments (see docs), but it definitely won't work until the yt-dlp bug mentioned in #139 is fixed. 

I actually have a PR open in yt-dlp that addresses that bug, but I'm just working through I'm getting it reviewed and addressing feedback. Hopefully soon!

**Comment by kieraneglin** [comment]
> A playlist in particular can have multiple videos on the same day which makes them see like the same season & episode number

Hmm, that's interesting. I did think about this in the moment, but I haven't fully considered how media center apps would handle that. 

I can't get too deep into it right now, but creating a _general_ fix for this is harder than it may initially seem. I'll see if I can get clever with it but I can't guarantee anything

**Comment by kieraneglin** [comment]
I think I have a plan for the duplicate season and episode number issue! I'll play around with that this week and reply here if  I actually figured it out 🤙🏻
