### ISSUE TITLE
[FR] Improve Media Center compatibility with videos released on the same day

### ISSUE THREAD

**Issue by kieraneglin** [kieraneglin/pinchflat#204]

**Comment by kieraneglin** [comment]
This one is tricky because getting those appended `01`, `02`... is more complicated than you may expect. The issue is that, in many cases, tracking that data with `yt-dlp`'s `playlist_index` would work with _some_ playlists (since videos are generally appended to playlists) but would be worse than useless for channels (since videos are prepended to channels).

An example: if you index a channel today its most recent video would have an index of 1. If the channel uploads another video, that _new_ video would now have an index of 1 and the video that previously had an index of 1 would now have an index of 2. That constant shifting makes it VERY hard to have a system that works reliably and as a user would expect.

You can get around this by reading the channel in reverse (ie: the oldest content gets indexed first), but completely breaks an advantage of Pinchflat (its uniquely short time between indexing and downloading new content). I'm not sure but I think this is how `ytdl-sub` does it but don't quote me on that.

---

Didn't mean to dig too deep there! I'm sure this is a solvable problem, but it's not the ezpz slam dunk it appears to be on the surface. I'll keep working on it and seeing what I can come up with!

**Comment by kieraneglin** [comment]
Thank you for the kind words (:

I wish I could do that - that's where my mind went as well BUT YouTube only returns the date and not the time. 

I was thinking about this more this evening and I think I have a possible solution that'll work in most/all cases. I'll be testing that out sometime this week

**Comment by kieraneglin** [comment]
@johnwarne @Gex2501 I have a fix for this in #221 which should be going out as part of `v0.1.16` later today!

There are some things to be aware of:
- Any media profile that used `{{ season_episode_from_date }}` in the output template will have to update that part to `{{ season_episode_index_from_date }}`
- This change is not retroactive so it'll only be applied to new media going forward. I hate to say it, but it's probably best to delete the source and re-download it once you've made the above change

Thanks for your patience here! This was a tricky one but I'm happy with the approach I ended up using 🎉

**Comment by kieraneglin** [comment]
@johnwarne much appreciated! The release with this change has been pushed and will be available in ~15 minutes 🤙 

Let me know how it works out for you and if I need to make any changes!

**Comment by johnwarne** [comment]
Great! In my testing it all seems to be working as intended with the new `{{ season_episode_index_from_date }}` template part. From what I can tell in testing, the latest episode from a day ends with 99 and it goes in reverse chronological order from there, e.g. if there are three episodes uploaded on a specific day, they will end in 97, 98, and 99. Success! Super appreciate this.

**Comment by kieraneglin** [comment]
Wooo! Love to hear it 🎉 - thanks for helping test!

As you saw the index will count down from 99 if it's a channel and count up from 0 if it's a playlist - this _should_ cover the expected behaviour for both those types of sources
