### ISSUE TITLE
[Support] Having problems adding sources

### ISSUE THREAD

**Issue by bunkerman** [kieraneglin/pinchflat#206]
I can add two sources, but after that it's not possible to add any new sources.

That's the output in the GUI
![grafik](https://github.com/kieraneglin/pinchflat/assets/7395381/7fc1890b-8b08-4c0b-a83e-28b41a9a3892)

and that's fro mthe logs
`11:32:55.985 request_id=F8q89rb0XIJmM6gAAdED [info] POST /sources
11:32:55.987 request_id=F8q89rb0XIJmM6gAAdED [info] [command_wrapper]: /usr/local/bin/yt-dlp called with: https://www.youtube.com/@CinemaTyler/ --simulate --skip-download --ignore-no-formats-error --playlist-end 1 --print-to-file %(.{channel,channel_id,playlist_id,playlist_title,filename})j /tmp/pinchflat/data/8f3fe09d9e6ae6fb5f5cf5a5ed7c0c9498ec5b3fdbdcc7442571061f08908c52.json --windows-filenames
11:33:03.689 request_id=F8q89rb0XIJmM6gAAdED [info] Sent 200 in 7704ms
11:33:03.809 [info] CONNECTED TO Phoenix.LiveView.Socket in 39µs
  Transport: :websocket
  Serializer: Phoenix.Socket.V2.JSONSerializer`

do I have to wait until everything is downloaded from the added sources? 

this is my portainer stack
`version: '3'
services:
  pinchflat:
    image: ghcr.io/kieraneglin/pinchflat:latest
    ports:
      - '8945:8945'
    volumes:
      - /portainer/Files/pinchflat:/config
      - /nas/video/youtube:/downloads
    restart: unless-stopped
    user: '1000:100'`

**Comment by kieraneglin** [comment]
Hey there, thanks for the report!

I just tried this on my machine and it worked just fine, but what you have here is clearly an issue! Before I start digging deeper, would you mind trying this again just as you had before? I have reason to think there was a temporary problem with YouTube that was breaking the way yt-dlp works.

It's a bit of a longshot, but it's worth trying! Please let me know how that goes

**Comment by bunkerman** [comment]
ok, it works now. I tried with several channels, but that one channel won't work https://www.youtube.com/@CinemaTyler/

thanks for now and great project!

**Comment by kieraneglin** [comment]
Great! Closing the issue - feel free to reply here or create another issue if it happens again
