### ISSUE TITLE
(Possible) [BUG] Download Cutoff Date not working for leap years (29/2)

### ISSUE THREAD

**Issue by justcallmelarry** [kieraneglin/pinchflat#209]
Randomly I did a quick check on todays' date - 60 days in order to get a date where I wanted to put the cutoff, which in this case ended up being 2024-02-29.

The cutoff date did not work as expected, and it started downloading loads of stuff from several years before this date.
At first I thought it was my fault as i added it after creating the source initially, so I removed the source and tried again.
Same thing happened, and this time I knew I had the correct settings there from start.
I then chose to set it to 2024-03-01 instead, and this time everything worked as expected.

So my suspicion is that is has something to do with the leap year date being special, and maybe that's not why it worked.

**Comment by kieraneglin** [comment]
Hmm, that's an interesting one! I tried with a new source (pics attached) and didn't see that issue, but stuff like this can be very temperamental sometimes.  I've tried both with channels that have and have not uploaded since 2024-02-29. Would you mind sending along the attribute details of your Source? It's on the main page when you're looking at a source

![Screenshot 2024-04-29 at 12 52 32 PM](https://github.com/kieraneglin/pinchflat/assets/569917/ba309ad0-cbcd-4439-8e20-36fa809e7a67)
![Screenshot 2024-04-29 at 12 53 23 PM](https://github.com/kieraneglin/pinchflat/assets/569917/554b5139-2296-407d-bc5b-d4a3e8699c80)
![Screenshot 2024-04-29 at 12 54 33 PM](https://github.com/kieraneglin/pinchflat/assets/569917/b9091595-0895-440c-9a7f-2c5c4eb27156)

**Comment by justcallmelarry** [comment]
I have removed the source twice and recreated, but here are the current ones:
<details>
<summary>Details</summary>
```
Raw Attributes
Media Profile: [Jellyfin](http://10.0.0.100:8945/media_profiles/2)
id: 4
description: Vintage Magic the Gathering videos on Monday, Wednesday, Friday! Streaming at http://www.twitch.tv/iamactuallylvl1 on Wednesdays at 6:30 PM EST and Saturdays at 1:00 PM EST MTG Vintage #MTGVintage #VintageMTG #VintageMagic #VintageMagicTheGahtering
uuid: 67373e3e-26b6-41ed-a798-b49d0a657853
inserted_at: 2024-04-29T18:49:45Z
updated_at: 2024-04-29T19:17:30Z
banner_filepath: 
fanart_filepath: 
poster_filepath: 
download_media: true
media_profile_id: 2
custom_name: IAmActuallyLvl1
collection_id: UCsozgtk-WCyOjSOK6mvs5lg
collection_name: IamActuallyLvL1
collection_type: channel
original_url: https://www.youtube.com/@IamActuallyLvL1
nfo_filepath: 
fast_index: false
title_filter_regex: 
series_directory: 
download_cutoff_date: 2024-03-01
last_indexed_at: 2024-04-29T19:17:30Z
index_frequency_minutes: 1440
output_path_template_override: 
retention_period_days: 60
```

**Comment by kieraneglin** [comment]
That's _really_ strange. I will need to see the logs to figure this out - would you mind attaching them? The log files are stored in your pinchflat config directory which should be accessible from your host computer

**Comment by kieraneglin** [comment]
Hey @justcallmelarry! Any chance you could attach your logs to help me get to the bottom of this?

**Comment by justcallmelarry** [comment]
@kieraneglin sorry! here you go.
[bu.log](https://github.com/kieraneglin/pinchflat/files/15172017/bu.log)

I took a look through it and what I think *might* have happened is that one of the many many download jobs were in progress when i added the date first time, and they just kept on going.
then when I reset the source maybe one of them was still going and that's why the folder was created on the disk?

I haven't had similar issues after the first two iterations of the source…

**Comment by kieraneglin** [comment]
Thanks for those!

I took a look over the logs and I didn't see anything unexpected in terms of downloads being triggered when they shouldn't. Deleting a source does cancel all of its download jobs, but the behaviour you was _will_ happen if a download completes in the fraction of a second between when the cancel request is made + when it completes (but this would only impact a maximum of two videos). 

It's not super likely, but this is something people run into (#166) and I reckon this is related! I'll close this for now but feel free to reopen if it keeps happening regularly
