### ISSUE TITLE
[Feat] Ignore based on more metadata

### ISSUE THREAD

**Issue by krohrsb** [kieraneglin/pinchflat#211]
I would be interested in being able to ignore on more criteria. Such as duration. Such as ignore if duration greater than a value. Or some may want to ignore less than.

**Comment by kieraneglin** [comment]
Hey there! Thanks for the report (:

I like the idea of this, but I think it's getting a little too granular. It's a pretty complicated feature to get right across _all_ the metadata I could filter on and it could lead to an overwhelming UI experience, even if it's opt-in.

I have a few ideas in the pipeline that could provide the ability for the user to add arbitrarily complicated filters AND add no in-app complexity, but I have no timeline on that and still have to assess if anyone would actually _use_ such a thing.

Again, I appreciate the report! Please re-open this issue or create a new one if there's something I missed

**Comment by crispybegs** [comment]
filtering stuff out based on duration would be really useful tbh. my wife wants a playlist, but only videos that are over 20 mins as the channel shoves every last 6-second bit of junk in the list which is of no interest to anyone

**Comment by TheScienceotter** [comment]
That sounds like a good approach to me. I don't think those examples are too contrived at all. I'm frequently filtering playlists to only extract videos by specific channels, that were livestreams, or are in a specific range of playlist indices. I have playlists based on themes that contain videos from lots of different channels on the same topic, but I might only want to download videos from a couple specific channels. 

Currently I am using the custom output templates feature to pass a --match-filter to yt-dlp to do this, and it works great (the ability to customise the output templates per-media profile was a big draw to pinchflat for me, as other similar software that supported custom output templates essentially only had one custom profile for the whole app). Of course my current approach is a bit of a hacky work-around, and while it works, the UI isn't aware of my filter so the "pending media" doesn't reflect what actually will be downloaded. 

I can certainly understand that supporting every filter option in the UI would be impractical, but if I could make the downloader aware of my filters by passing it the yt-dlp --match-filter arguments or giving it a python script, then that would be ideal.
