### ISSUE TITLE
Pinchflat creates folders with permission issues

### ISSUE THREAD

**Issue by MARAllMighty** [kieraneglin/pinchflat#213]
Hello there,

When Pinchflat creates a folder for the source its downloaded, that folder is only available to the root account on my Unraid box. I tried setting the PGID and PUID appropriately without success. 

I've included a screenshot of my Unraid template settings, any help would be appreciated!
<img width="1138" alt="Screen Shot 2024-04-30 at 3 47 16 PM" src="https://github.com/kieraneglin/pinchflat/assets/139924320/1854fb03-4e1c-4d71-9eeb-b9cfc72b5781">

**Comment by jaycedk** [comment]
Did you read this there is a section about permissions
https://github.com/kieraneglin/pinchflat

I have this under Extra parameters i my unraid install
--user 99:100

**Comment by kieraneglin** [comment]
Hey there! Thanks for the report (:

That's very strange, given that Unraid should be fire-and-forget. What I can say for sure is that the `PUID` and `PGID` variables are unneeded - those don't actually _do_ anything by default and instead are a convention put in place by the Linuxserver team for their images back before Docker had a `--user` option.

As the other comment alluded to, I have put `--user 99:100` in the `Extra Parameters` section (you may have to toggle the advanced view in the upper right to see it). I suspect you'll have to change the `99:100` to the PUID and PGID you typically use for other docker containers.

---

To me this does seem indicative of some other issue with Docker/Unraid config, but this is not my area of expertise so I'd recommend starting with changing that `99:100` as described above and seeing what that changes 🤞

**Comment by MARAllMighty** [comment]
Hello Kieraneglin,

Thank you for the input. I have tried using the --users:99:100 in Extra Parameters previously without success. I have never had docker folder issues previously, and use 99:100 for my other containers following the Linuxserver standard.

The files that are downloaded are so locked down that my Plex can't see them either so I'm really not sure what is going on :/

**Comment by jaycedk** [comment]
Thats strange here is my folder permissions and docker setup
![image](https://github.com/kieraneglin/pinchflat/assets/17232146/e500478a-f4fb-481b-bfe1-2e8555cb3037)

![image](https://github.com/kieraneglin/pinchflat/assets/17232146/db903c8a-f452-4958-963e-1fa33befdeff)

But you can change the owner ship and r/w permissions directly in unraid.
Or create a new share and try again.
As said I have no problem with the docker or permissions, i Unraid.

**Comment by kieraneglin** [comment]
There's almost no chance the permissions are so locked down that Plex can't even _see_ them so I suspect there's something else going on here.

Do me a favour - open a new console session in _Unraid_ (not the Pinchflat docker container) and do the following:

- Navigate to `/mnt/user/media/Web`
- Navigate into the directory that holds some YouTube videos you've downloaded. You're looking for a directory that directly contains a video file
- Paste the output of `ls -la`

**Comment by kieraneglin** [comment]
@MARAllMighty hey there! Have you had any luck here?

**Comment by MARAllMighty** [comment]
Hello there,

thank you for all your help! What ended up working was blowing away the entire container and recreating the folder structure from scratch. 

Downloads are now happening under the correct permissions structure and Plex can see them as well

Thanks again! This can be closed

**Comment by MARAllMighty** [comment]
Closing
