### ISSUE TITLE
Incorrect Notification

### ISSUE THREAD

**Issue by Gex2501** [kieraneglin/pinchflat#215]
So I have Pushover configured for my notifications. Works great. However, I added the channel @StarTalk and set it to NOT download. Index only. And that works as expected. But the notification I got when it had finished indexing indicated it would start downloading when it was not. See screenshot...

I suppose the notification messages need fixing?

![IMG_0713](https://github.com/kieraneglin/pinchflat/assets/63863/5a85929d-094e-4428-9c12-2ba76cb066d7)

**Comment by kieraneglin** [comment]
Hey there! Thanks for the report (:

you're right - silly oversight. I'll get that fixed up for the next release!

**Comment by kieraneglin** [comment]
Fixed! That'll be going up with the next release sometime this week (:

**Comment by Gex2501** [comment]
Woot! 🙌
