### ISSUE TITLE
[FR] Add a button for testing notifications

### ISSUE THREAD

**Issue by justcallmelarry** [kieraneglin/pinchflat#217]
If I'm spamming too many issues, please let me know and I will calm the flood. :)

When testing the notifications (Apprise, and hopefully in the future more generic webhooks 😉) it is a bit "annoying" adding a test source in order to test if your setup is working.

It would be nice if there was a button to send a test notification while you are setting it up, which just sends some random test string as title and body.

Here is a very poorly mocked example of how it could look:
<img width="702" alt="image" src="https://github.com/kieraneglin/pinchflat/assets/24991021/ab5e53ec-40cd-4fcb-a958-ca61b1b736b0">

I realise that it's mostly meant to work with Discord, but there are many out there who run their own Apprise API's.

**Comment by kieraneglin** [comment]
Good idea! I'll put it on the list

**Comment by kieraneglin** [comment]
This is done and will come out with the next release!

![Screenshot 2024-05-03 at 3 42 55 PM](https://github.com/kieraneglin/pinchflat/assets/569917/cfd46a3e-4425-4542-9d33-7a5b954f1e21)
