### ISSUE TITLE
[FR] Plugin system to add other sites

### ISSUE THREAD

**Issue by jonatino** [kieraneglin/pinchflat#220]
yt-dlp supports a bunch of websites. It'd be nice to be able to write plugins to support archiving of other sites like Rumble since yt-dlp support them natively.

**Comment by jonatino** [comment]
Cancel that, didnt see #177

**Comment by kieraneglin** [comment]
I haven't checked with that site (nor have I ever heard of it), but it's worth testing out! Again, I likely won't go out of my way to support any non-youtube site but there's a 50/50 chance it'll work out of the gate.

Just keep in mind the caveats I posted in #177 and please comment there if it ends up working 🤙
