### ISSUE TITLE
[FR] History/Changelog on the Homepage

### ISSUE THREAD

**Issue by drewstopherlee** [kieraneglin/pinchflat#227]
First things first, this app has quickly become an integral part of my media aggregation setup, so thank you for that!
I had an idea for the homepage that maybe a table could be displayed beneath the profile/source/items widgets at the top. Here's my idea for the layout:
| Media Title                                                                        | Upload Date | Index Date           | Download Date        | Source                   |
|------------------------------------------------------------------------------------|-------------|----------------------|----------------------|--------------------------|
| Bittersweet Reunions \| Critical Role \| Campaign 3, Episode 93                    | 2024-05-06  | 2024-05-07T04:09:27Z | 2024-05-07T04:23:55Z | Critical Role Campaign 3 |
| Hawaiian Hits with Gabby Reece and Laird Hamilton \| Something's Burning \| S3 E21 | 2024-04-30  | 2024-05-01T16:27:39Z | 2024-05-01T16:35:50Z | Something's Burning      |

Not sure how feasible this idea is, but I think it would be helpful to be able to quickly see the most recently indexed/downloaded items when I log in.

**Comment by kieraneglin** [comment]
I like it! Thanks for the suggestion

**Comment by kieraneglin** [comment]
Done! Thanks again for the idea - I like how that turned out

That'll be going up with the next release (v0.1.18) that should go out sometime this week

**Comment by drewstopherlee** [comment]
Awesome! I'm excited to see it in the new release!! :blush:

**Comment by kieraneglin** [comment]
I just published the release and it'll be up in about 20 mins!

**Comment by drewstopherlee** [comment]
Awesome, I'll update once I get home and check it out! Thanks again!!

**Comment by drewstopherlee** [comment]
@kieraneglin the new homepage looks great btw! Exactly what I was hoping for!!
