### ISSUE TITLE
[Triage] {{ upload_date_index }} returns "NA" instead of the actual index number

### ISSUE THREAD

**Issue by foggy75** [kieraneglin/pinchflat#228]
I'm using Pinchflat v0.1.17, which adds the new indexed variables.

I created a Media profile for use with Plex (and Absolute Series Scanner + YouTubeSeries Agent), and I'm using the following output_path_template:
`/{{ source_custom_name }} [{{ source_collection_id }}]/Season {{ season_from_date }}/{{ source_custom_name }} - {{ upload_yyyy_mm_dd }}{{ upload_date_index }} - {{ title }} [youtube2-{{ id }}].{{ ext }} `

However, when downloading files, the filename is showing NA instead of the index number, although that the index number exists for the file when looking at the properties for the downloaded file.

I noticed that when using `{{ season_episode_index_from_date }}` the index does get filled out properly into the filename. Unfortunately I can't use that field as Plex's scanner does not properly index the files with that field in the filename. It expects YYYY-MM-DDII as format for date-based series files.... 

[json_files.zip](https://github.com/kieraneglin/pinchflat/files/15239662/json_files.zip)

**Comment by kieraneglin** [comment]
Hey there, thanks for the report (:

Try `{{ media_upload_date_index }}` - I try to add the "target" as a prefix to disambiguate, just in case

Let me know if that works out!

**Comment by foggy75** [comment]
Hi, 
I just tried it, and that works! Thank you :)
