### ISSUE TITLE
EFF Donation Receipts

### ISSUE THREAD

**Issue by kieraneglin** [kieraneglin/pinchflat#234]

**Comment by kieraneglin** [comment]
Backfilling existing donations:

## 2024-04-29

$15USD donation for PayPal transactions ending in `1582A`, `82906`, and `1711F`

<img src="https://github.com/kieraneglin/pinchflat/assets/569917/84c175e0-d848-439f-adec-e977bd929041" width="500">

## 2024-04-17

$10USD donation for PayPal transactions ending in `1415S` and `39311`

<img src="https://github.com/kieraneglin/pinchflat/assets/569917/f812169d-bc70-476b-8c65-52ed629740d9" width="500">

## 2024-04-01

$10USD donation for PayPal transactions ending in `9702D` and `5350X`

<img src="https://github.com/kieraneglin/pinchflat/assets/569917/a13d6d8d-b1c7-47f4-828b-81813809c9f5" width="500">

## 2024-03-19

$10USD donation for PayPal transactions ending in `1621G` and `0271A`

<img src="https://github.com/kieraneglin/pinchflat/assets/569917/7fe0166c-0eac-430b-a4fe-c7eb1f55c2a9" width="500">

**Comment by fourg** [comment]
![Screenshot 2024-09-28 091449](https://github.com/user-attachments/assets/e854c844-1412-4e73-9328-51f9d4c564c1)

**Comment by maxiride** [comment]
![immagine](https://github.com/user-attachments/assets/b5b37425-a9fd-4d5b-90f1-8852aa814f08)

**Comment by resonanttoe** [comment]
Amazing stuff and the support you offer is like no other!
![Screenshot 2025-01-08 at 10 57 54](https://github.com/user-attachments/assets/bf55c1e0-4615-4408-a7df-6ea89ef4a213)

**Comment by hthornwell** [comment]
![EFF_Donation_2024](https://github.com/user-attachments/assets/34490d0f-7391-4563-90a9-abaca168d336)

Forgot to post after donating back in September - might donate again now, fantastic org :)

**Comment by Nezteb** [comment]
✊ 

![Image](https://github.com/user-attachments/assets/46b3acee-44f3-4f29-a408-76ec58f4f5d2)

**Comment by kieraneglin** [comment]
@Nezteb that rules so hard! You love to see it

**Comment by philips** [comment]
<img width="1196" alt="Image" src="https://github.com/user-attachments/assets/de6f6b7c-716c-442d-81ec-e56d5dee939e" />
