### ISSUE TITLE
RSS feed not updating

### ISSUE THREAD

**Issue by clayb91** [kieraneglin/pinchflat#240]
It seems like on my install that some RSS feeds have stopped updating. Media is still being indexed and downloaded for the sources, but the feed does not update to include the new media.

**Comment by clayb91** [comment]
Actually, it looks like I am running into a feed limit of 300 items. I looked through the docs and don't see this limit noted anywhere. Is this normal and expected? If so, I may need to adjust how I am using this.

**Comment by kieraneglin** [comment]
Hey there! Thanks for the report (:

If I'm honest, I can't remember _why_ I put that limit of 300 items. I'll look into whether I can safely remove that

**Comment by kieraneglin** [comment]
Ah, I remember! The podcast app I've been testing on gets _really_ sluggish when importing > ~750 items so I added a safe limit to keep things snappy. But I did this testing early in the process and I didn't re-test after I had made some performance improvements.

There also appeared to be a bug where the ~300 it picked wasn't necessarily the most recently uploaded media - I'll fix that and bump the limit which _should_ resolve this issue in many more cases. I'm hesitant to remove the limit entirely for now, but I'll probably do so if this continues to be an issue

**Comment by clayb91** [comment]
That makes sense! It would be nice if the RSS feed was updated to reflect only media that was downloaded. Otherwise, as the sources reach 300 items (or whatever the new limit will be) the RSS will stop working.

**Comment by kieraneglin** [comment]
It should already do that! If you take a look [here](https://github.com/kieraneglin/pinchflat/blob/master/lib/pinchflat/podcasts/podcast_helpers.ex#L26), you can see that it only includes media that's confirmed to exist on-disk. But please let me know if you're seeing media that's not saved getting included in the feed!

**Comment by clayb91** [comment]
Yep, you're right! I had to remove the feed and add it back for the app to clear the cached list. Still has 300 items, but the deleted items are gone. Thanks!

**Comment by kieraneglin** [comment]
Turns out I needed to push out a release today to help triage a bug, so this will actually be out there in about 30 minutes
