### ISSUE TITLE
Upgrade to Pro modal: Wrong correct input

### ISSUE THREAD

**Issue by kristianbinau** [kieraneglin/pinchflat#242]
Upgrade to pro modal says:
https://github.com/kieraneglin/pinchflat/blob/d57554822613aec425a502e92383f8e32b41b196/lib/pinchflat_web/components/layouts/partials/upgrade_modal.heex#L24

But the input wants:
https://github.com/kieraneglin/pinchflat/blob/d57554822613aec425a502e92383f8e32b41b196/lib/pinchflat_web/components/layouts/partials/upgrade_button_live.ex#L33

**Comment by kieraneglin** [comment]
Hey there! Thanks for the report (:

This is actually intentional - I want to make pro as easy to enable as possible. I could see how the sentence could be interpreted as "To unlock Pro, simply type `got it`!" instead of "To unlock Pro, simply type `got it!`", hence that change

**Comment by kieraneglin** [comment]
actually, on second thought I think you're right. I'll nix the `!` from the helper text

**Comment by kristianbinau** [comment]
Yeah, It took me a few minutes to understand that it wasn't "got it!", but "got it". Thanks for the quick solving : )

**Comment by kieraneglin** [comment]
Yeah, my bad! I had thought I was just checking for a substring there, but I forgot I was actually checking for a complete match. 

Thanks for the report! That'll be going out with the next release later today
