### ISSUE TITLE
Log spam: [debug] EOF reached, waiting before trying to read new lines

### ISSUE THREAD

**Issue by lukyjay** [kieraneglin/pinchflat#253]
Hey

Love the app so far. Just added a lot of channels and my docker logs are being spammed with an EOF debug line. Two questions:
1. What is the error, should I be concerned?
2. How can I disable debug logging with the docker container? Can't find anything via search or wiki

I did not see this message appear on v0.1.17, it was only when I updated to 2024.5.16. It's entirely possible that's coincidental, thought, as I just added about 40 new Youtube channels to be indexed.

Thank you!

> 20:23:07.209 [debug] QUERY OK source="media_profiles" db=0.1ms idle=4.9ms
> SELECT m0."id", m0."name", m0."redownload_delay_days", m0."output_path_template", m0."download_subs", m0."download_auto_subs", m0."embed_subs", m0."sub_langs", m0."download_thumbnail", m0."embed_thumbnail", m0."download_source_images", m0."download_metadata", m0."embed_metadata", m0."download_nfo", m0."sponsorblock_behaviour", m0."sponsorblock_categories", m0."shorts_behaviour", m0."livestream_behaviour", m0."preferred_resolution", m0."inserted_at", m0."updated_at", m0."id" FROM "media_profiles" AS m0 WHERE (m0."id" = ?) [1]
> 20:23:07.210 [debug] QUERY OK source="media_items" db=0.2ms idle=4.8ms
> SELECT 1 FROM "media_items" AS m0 INNER JOIN "sources" AS s1 ON s1."id" = m0."source_id" INNER JOIN "media_profiles" AS m2 ON m2."id" = s1."media_profile_id" WHERE (m0."id" = ?) AND (m0."prevent_download" = 0) AND (m0."media_filepath" IS NULL) AND ((s1."download_cutoff_date" IS NULL) OR (m0."upload_date" >= s1."download_cutoff_date")) AND (  CASE
>     WHEN shorts_behaviour = 'only' AND livestream_behaviour = 'only' THEN
>       livestream = true OR short_form_content = true
>     WHEN shorts_behaviour = 'only' THEN
>       short_form_content = true
>     WHEN livestream_behaviour = 'only' THEN
>       livestream = true
>     WHEN shorts_behaviour = 'exclude' AND livestream_behaviour = 'exclude' THEN
>       short_form_content = false AND livestream = false
>     WHEN shorts_behaviour = 'exclude' THEN
>       short_form_content = false
>     WHEN livestream_behaviour = 'exclude' THEN
>       livestream = false
>     ELSE
>       true
>   END
> ) AND ((s1."title_filter_regex" IS NULL) OR regexp_like(m0."title", s1."title_filter_regex")) LIMIT 1 [39]
> 20:23:07.210 [info] Kicking off download for media item #39 (-duJtlw394U)
> 20:23:07.211 [debug] EOF reached, waiting before trying to read new lines
> 20:23:08.152 [debug] EOF reached, waiting before trying to read new lines
> 20:23:08.212 [debug] EOF reached, waiting before trying to read new lines
> 20:23:09.153 [debug] EOF reached, waiting before trying to read new lines
> 20:23:09.213 [debug] EOF reached, waiting before trying to read new lines

**Comment by jaycedk** [comment]
You can set LOG_LEVEL in your docker compose.
Here is a example from Unraid
![image](https://github.com/kieraneglin/pinchflat/assets/17232146/7ec41d45-a8a7-4994-9cc2-9afab30ceba0)
![image](https://github.com/kieraneglin/pinchflat/assets/17232146/a4954d91-d467-4eb7-989a-293c8c1e82e0)
About you 1st question you will have to wait for dev.

**Comment by kieraneglin** [comment]
Hey there! Thanks for the report (:

1. As the other comment mentioned, setting the `LOG_LEVEL` env var to `info` should do what you need! You're totally correct in saying this is new behaviour for most people - I had received a few bug reports that _really_ needed debug logs so I made it the default log level pretty recently. I'll add a blurb to the README sometime soon
2. The `EOF ...` log entry is totally [expected](https://github.com/kieraneglin/pinchflat/blob/94c0cf99707c33c2d89be8313489e0f2afcad241/lib/pinchflat/slow_indexing/file_follower_server.ex#L109). That message comes from a module that proactively reads an output file created by yt-dlp for the purpose of downloading media while a source is in the process of being indexed

Let me know if you have any other questions!

**Comment by lukyjay** [comment]
Thanks both!  Noting for future users that it is case sensitive too.
