### ISSUE TITLE
[FR] Improve removing logic from "Pending media"

### ISSUE THREAD

**Issue by Pinkbyte** [kieraneglin/pinchflat#257]
Related to #111

It seems that currently it is possible to remove unwanted&stuck videos(mistakenly added into playlist to archive and not downloaded for some reason) from "Pending media" only by clicking on 'Delete and Ignore' on video item. But there are no place in web interface to list/clear ignored videos list - as far as i understand the only ways to clear ignored list is either to dive into database manually or remove/re-add source (which seems to trigger re-downloading of all videos).

**Comment by kieraneglin** [comment]
Ah, good call! You actually should be able to search for the media in the upper right if you know its name, but I'll see if I can add a better solution

**Comment by kieraneglin** [comment]
Ended up being easier than I thought! I've added a new tab to the source view that shows media that's not pending or downloaded (ie: media that's been ignored, either manually or because of your profile/source's settings)

that'll be out in the next release (either later this week or early next week)

**Comment by Pinkbyte** [comment]
I have installed v2024.05.24 release - tab "Other" appears, but it is not possible to manually delete video from database entirely, only to move it into pending state - but as this video is non-downloadable for some reason - it will stuck in pending state.

Can you please add possibility to manually remove stuck/ignored video from database? It will not be added again, if i remove it from my Youtube playlist first
