### ISSUE TITLE
[FR] Export & import settings

### ISSUE THREAD

**Issue by mbhkoay** [kieraneglin/pinchflat#350]
Trying to export the settings and import it again to start over. 

To have the sources and profiles exported as a file, that pinchflat will be able to import again, preferably in a format that can be edited, providing an alternative method to modify the settings. 

Alternatively can copy & paste the configurations to a text file and redo everything. 

Additional context:
Messed up somewhere....There is just 1 source that throws an internal server error while trying to access it. The rest is working fine. 

Or is there a way to delete a source by deleting a file somewhere?

**Comment by kieraneglin** [comment]
I've tried this a few different ways but I haven't found an approach for restoring in this way that really feels worth doing. With the addition of #399, I'd say the best way to achieve this is to copy over your SQLite database file and run a file sync (see #399) if needed

Thanks again for the report (:
