### ISSUE TITLE
Nebula almost works, it only needs a small change to video URLs

### ISSUE THREAD

**Issue by mgabor3141** [kieraneglin/pinchflat#381]
I was originally going to comment this under #177 but an issue is better for discussion.

Nebula almost works, it just has an issue retrieving metadata fields from videos. I have done some investigation and the issue seems to be the following. (And also very simple to fix if I'm not mistaken.)

## Problem

The Nebula extractor uses the `#__youtubedl_smuggle` URL parameter to tell the video download step that it doesn't need to fetch the metadata, because we already have it from the playlist metadata step. [Code](https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/extractor/nebula.py#L224)

This parameter gets saved into the Pinchflat video database entry with the rest of the URL:

![image](https://github.com/user-attachments/assets/b1e31505-d07a-44d4-af42-7f1f508569a3)

This means that when Pinchflat starts the job to download this individual URL we skip fetching any metadata:

![image](https://github.com/user-attachments/assets/4db436db-5d86-4cc5-957d-4e2f688b47e2)

Note that the title field is wrong, all dates are null, many fields are missing which would normally be present, etc. This impacts the output filenames, and changing the output format doesn't help either. This data is missing at this point in the process.

![image](https://github.com/user-attachments/assets/0c7da7e1-6d35-4c56-a039-6e532defce01)

I have tried to nail down that this is in fact the root cause by running `yt-dlp` with the `-j` parameter to see the resulting json fields. I ran it on both the playlist URL, the video URL, as well as the video URL with the `#__youtubedl_smuggle` parameter, and I got the incorrect metadata only in the last case. I have also confirmed through the `--verbose` flag that when  `yt-dlp` downloads the playlist it also fetches the individual videos with this smuggle parameter, but since it's in the process of downloading the playlist it's not a problem then.

```
[download] Downloading item 6 of 6
[nebula:video] Extracting URL: https://nebula.tv/videos/getaway-trailer/#__youtubedl_smuggle=%7B%22id%22%3A+%22video_episode%3A163cc414-0d92-4753-a7d9-b6a3981a6033%22%7D
```

## Possible solution

Get rid of this smuggle parameter.

One option is to strip it [here](https://github.com/kieraneglin/pinchflat/blob/master/lib/pinchflat/yt_dlp/media.ex#L42), but preferably it should be stripped when the video URL is inserted into the database.

The easy option is to just throw away the `#` and everything after it, but ideally only this parameter would be removed as there could be cases where other `#` params are important. Not with YouTube though as far as I know.

## Possible solution where an upstream fix is needed

`yt-dlp` has a a [field in the output metadata](https://github.com/yt-dlp/yt-dlp/tree/master?tab=readme-ov-file#output-template) that's documented as follows:

> - `webpage_url` (string): A URL to the video webpage which, if given to yt-dlp, **should yield the same result again**

In an ideal scenario this would already contain the video URL with the smuggle parameter removed. Unfortunately this is not the case, so `yt-dlp` fails to deliver on this "same result" promise.

![image](https://github.com/user-attachments/assets/6441830a-6961-4e60-80e7-11cd7a72e98f)

---

In any case I'd be happy to contribute a fix, but I've never done Elixir development before. I do have some experience with functional programming, so I might be able to put together a simple change, but I would definitely like some direction first.

Would a change like this be desired/acceptable in this project as it's not needed for YouTube functionality?

**Comment by kieraneglin** [comment]
I'll leave this for someone who's ready to take it on! In the meantime, I'm going to close this issue 🤙
