### ISSUE TITLE
[Triage] Duplicate video after Youtube video name change

### ISSUE THREAD

**Issue by benhoIIand** [kieraneglin/pinchflat#389]
**Describe the bug**
When the publisher changes the title of the Youtube video, it results in 2 copies of that video being downloaded

**To Reproduce**
Steps to reproduce the behaviour:

1. Add a new source
2. Index them as usual and download a video
3. Change the title of that video
4. Duplicate video is download and named using the new video title

**Expected behavior**
I am only expecting to have 1 copy of the video downloaded

**Screenshots**
Here's an example of the result I see with both videos being present on the system
![image](https://github.com/user-attachments/assets/f54d03fd-caea-4ab4-aa9e-5d11c8942b73)

**Additional context**
- I am using fast indexing

**Comment by benhoIIand** [comment]
Here's the downloaded JSON - https://gist.github.com/benhoIIand/0e14baed66092894aa480092b0cc71b5

Yes, the dates are the date that it was downloaded. It seems the publisher changed the title after a few days. The media ID in Youtube wasn't changed so it wasn't removed and re-uploaded.

**Comment by kieraneglin** [comment]
Thanks, that helps a lot!

I think it's the automatic media re-download logic that's doing this. I'll dig in and see what I can find!

**Comment by kieraneglin** [comment]
This is fixed in #396! It's not a retroactive fix, but it'll stop the issue from happening going forward.

That'll go out with the next release - probably later this week 🤙

**Comment by benhoIIand** [comment]
Great news - thanks a lot
