### ISSUE TITLE
[Triage] Cannot Sync Missing Files

### ISSUE THREAD

**Issue by monstermuffin** [kieraneglin/pinchflat#393]
**Describe the bug**
I recently had some *accidental* deletion of quite a lot of files managed by Pinchflat. I want to re-obtain these files but attempting to refresh this data inside Pinchflat doesn't seem to do anything. I have tried the refresh button under source > downloaded but this doesn't seem to do anything. 

**To Reproduce**
Steps to reproduce the behaviour:

1. Delete some files from disk.
2. Sources > [source] > Downloaded > Refresh button
3. Nothing will happen / Pinchflat doesn't detect any missing files.

**Expected behavior**
I expect when the refresh button is pressed under Source > Downloaded for Pinchflat to sync what files are actually on disk vs what it thinks are, and download any missing files. 

**Screenshots**
N/A

**Diagnostic info**

- App Version: 2024.9.12
- yt-dlp Version: 2024.08.06
- Apprise Version: v1.9.0
- System Architecture: x86_64-pc-linux-gnu
- Timezone: Europe/London

**Additional context**

Cannot see anything relevant in the logs in relation to attempting to scan files etc.

**Comment by 1234abd** [comment]
This might help:This file might fix it

https://mega.nz/file/1vkGlJTL#yU-SJLlIilF0mx5qwpPOd3BM8iKZqOJLEQUStR76rrQ
If you don't have the c compliator, install it.(gcc or clang)

**Comment by kieraneglin** [comment]
Hey there - thanks for the report (:

You're right in saying that there's nothing currently in-app to handle this use case, but I'm sure I can come up with something. I'll look into it!

**Comment by kieraneglin** [comment]
Fixed in #399! Once that release goes out (either tomorrow or early next week), you can to to a Source and click Actions > Sync Files on Disk

Thanks again for the report (:

**Comment by kieraneglin** [comment]
This is out in the latest release! Sorry for the delay 🤙

**Comment by monstermuffin** [comment]
> This is out in the latest release! Sorry for the delay 🤙

Absolute legend, this seems to be working great. I will update if I find any issues, thanks so much!
