### ISSUE TITLE
[FR] Automatic removal of background music from videos (vocal remover feature)

### ISSUE THREAD

**Issue by Iliannnn** [kieraneglin/pinchflat#403]
I would like to see the implementation of an automatic vocal remover feature that can effectively isolate and remove background music from videos with minimal user input.

**Comment by kieraneglin** [comment]
Hey again! Thanks for the report (:

This feels like it's outside the purview of the app at this point. There are things like [lifecycle scripts](https://github.com/kieraneglin/pinchflat/wiki/%5BAdvanced%5D-Custom-lifecycle-scripts) that can let a user set this up if they so choose.

That said, I'm curious about the idea overall and I wonder if this would be a better recommendation for the `yt-dlp` team (in a similar vein to their Sponsorblock integration). Is there a popular/recommended tool that people use for this task?

**Comment by Iliannnn** [comment]
Yeah, it might be a bit specific and outside of the scope of the app. Great! I might experiment and see if I can pull it off with a script.

Might be something for the yt-dlp team, but I don't think they have any plans of integrating it. [Spleeter](https://github.com/deezer/spleeter) is used a lot, it has a [Docker image](https://hub.docker.com/r/researchdeezer/spleeter) too.

**Comment by kieraneglin** [comment]
I've thought this over and I just don't think it's a fit for this project at the moment. But it's a really good idea and I recommend you pitch it to the `yt-dlp` team as a feature request if you haven't already!

**Comment by Iliannnn** [comment]
https://github.com/yt-dlp/yt-dlp/issues/11239

**Comment by Iliannnn** [comment]
Hey, I got the response below. Do you think there would be a possibility to integrate this within Pinchflat using a custom yt-dlp command for this or would I need to write a custom postprocessing plugin?

https://github.com/yt-dlp/yt-dlp/issues/11239#issuecomment-2409139374

**Comment by kieraneglin** [comment]
@Iliannnn you should be able to add that in now as a post-processing step using lifecycle scripts, but I think it'd be most compelling as a proper yt-dlp post-processing plugin. I don't have the capacity to take that on at the moment, but I'm sure there are others who would be interested in something like that!
