### ISSUE TITLE
[Triage] Error when trying to add a new source

### ISSUE THREAD

**Issue by ping-localhost** [kieraneglin/pinchflat#404]
**Describe the bug**
[Issue #391](https://github.com/kieraneglin/pinchflat/issues/391) happened again whilst trying to add `https://www.youtube.com/feed/subscriptions`.

**To Reproduce**

- Install a fresh copy of pinchflat
- Try to add your YouTube subscriptions
- See error.

```
**Status**:
`500`

**Reason**:
`%CaseClauseError{term: {:error, %Jason.DecodeError{position: 0, token: nil, data: ""}}}`

**Stacktrace**:
    (pinchflat 2024.10.2) lib/pinchflat/sources/sources.ex:185: Pinchflat.Sources.add_source_details_to_changeset/2
    (pinchflat 2024.10.2) lib/pinchflat/sources/sources.ex:78: Pinchflat.Sources.create_source/2
    (pinchflat 2024.10.2) lib/pinchflat_web/controllers/sources/source_controller.ex:76: PinchflatWeb.Sources.SourceController.create/2
    (pinchflat 2024.10.2) lib/pinchflat_web/controllers/sources/source_controller.ex:1: PinchflatWeb.Sources.SourceController.action/2
    (pinchflat 2024.10.2) lib/pinchflat_web/controllers/sources/source_controller.ex:1: PinchflatWeb.Sources.SourceController.phoenix_controller_pipeline/2
    (phoenix 1.7.14) lib/phoenix/router.ex:484: Phoenix.Router.__call__/5
    (pinchflat 2024.10.2) lib/pinchflat_web/endpoint.ex:1: PinchflatWeb.Endpoint.plug_builder_call/2
    (pinchflat 2024.10.2) lib/pinchflat_web/endpoint.ex:1: PinchflatWeb.Endpoint.call/2
```

**Diagnostic info**

- App Version: 2024.10.2
- yt-dlp Version: 2024.09.27
- Apprise Version: v1.9.0
- System Architecture: x86_64-pc-linux-gnu
- Timezone: UTC

**Additional context**

[pinchflat-logs-2024-10-06.txt](https://github.com/user-attachments/files/17270020/pinchflat-logs-2024-10-06.txt)

**Comment by kieraneglin** [comment]
Hey there! Thanks for the report (:

This is expected in a sense since you shouldn't be able to add that feed as a source (since it's neither a channel nor a typical playlist), but I should probably add a more friendly error message

**Comment by ping-localhost** [comment]
> Hey there! Thanks for the report (:
> 
> This is expected in a sense since you shouldn't be able to add that feed as a source (since it's neither a channel nor a typical playlist), but I should probably add a more friendly error message

Oh that's too bad, I would've liked to download my subscriptions, so I can watch them via Plex. Adding all my channels is not really what I want (and it would take forever, haha).

I guess this is outside the scope of pinchflat. Thanks for the quick reply.

**Comment by kieraneglin** [comment]
@ping-localhost the biggest issue is that `yt-dlp` doesn't have a mechanism to accomplish this in the way a user would expect. So for now it's off the table, unfortunately!

Also, I'm going to re-open this issue as a reminder-to-self to add a better error message for this case
