### ISSUE TITLE
[FR] Using Youtube RSS feed for channels

### ISSUE THREAD

**Issue by sean89503** [kieraneglin/pinchflat#407]
Using the RSS feed of a channel would eliminate the need for an API a user to check as many times as you want.
Limitations are that you limited to the latest **15** videos
**Channel Example:** `https://www.youtube.com/channel/UCzsjHlc0WRwZYwlinsmtM4w`
**RSS Example:** `https://www.youtube.com/feeds/videos.xml?channel_id=UCzsjHlc0WRwZYwlinsmtM4w`

**Comment by kieraneglin** [comment]
Hey there! Thanks for the report (:

RSS is already the [main mechanism](https://github.com/kieraneglin/pinchflat/blob/85feb672994dccfe5e6d6826fbb376f90ebe4da2/lib/pinchflat/fast_indexing/youtube_rss.ex) used by fast indexing. The downside is that RSS can take a very long time to update for smaller channels (upwards of 2 hours in some cases), so I offer the alternative of using the [YouTube API](https://github.com/kieraneglin/pinchflat/wiki/Generating-a-YouTube-API-key) to perform fast indexing more reliably.
