### ISSUE TITLE
Add setting to not fully download channel when newly added as source

### ISSUE THREAD

**Issue by anarqist** [kieraneglin/pinchflat#410]
Hi,

is there any way to prevent pinchflat from downloading every video from a channel when you initially add it as a source and only download/add new videos starting when you add the source? 

On a fresh install if you add multiple sources and they all contain 100+ videos or even 1000+ videos it takes forever and the risk of getting blocked temporarly is possible I guess. 

I would like to have an option to say enable when adding a new source only download videos uploaded after I added it as a source and others can download the whole history. 

Is that possible? I check all the settings but could not find anything. 

Thanks in advance!

PS: Really great app with very low resources needed to run! 🫶

**Comment by kieraneglin** [comment]
Hey there! Thanks for the report (:

On the Source form you can set `Download Cutoff Date` to whatever date you want and only videos uploaded after that date will be downloaded. So if you want to get every video from September onward, you'd put `2024-08-01`. Or you can set it to today's date (`2024-10-11`) to only get new content while ignoring old stuff 🤙
