### ISSUE TITLE
[FR] Add Option for Post-Processing

### ISSUE THREAD

**Issue by SenorFusion** [kieraneglin/pinchflat#411]
**Is your feature request related to a problem? Please describe.**
I have to have my files archived in a certain format - specifically mp4 / h264 / aac

I understand it's hard or impossible to get yt-dlp to pull the exact format you want every single time.

**Describe the solution you'd like**
Add a Config setting:
If you dont get the video/audio codec you requested > then --use-postprocessor of ffmpeg to convert it to the format you wanted.

**Describe alternatives you've considered**
The only alternative I can see if going back to another service like TA that will let me manage this.

**Additional context**
I do understand that Pinchflat is somewhat opinionated about how videos should be downloaded. 

I understand if this is out of scope for the project, but without a way to force into the formats I need, I end up having to do a bunch of manual post processing or scripts, which kind've defeats the purpose of a nice easy tool.

Thanks for considering!

**Comment by kieraneglin** [comment]
Hey there! Thanks for the report (:

Does [this](https://github.com/kieraneglin/pinchflat/wiki/%5BAdvanced%5D-Custom-yt%E2%80%90dlp-options) let you do what you need?

**Comment by kieraneglin** [comment]
Please feel free to open if that doesn't address your issue!
