### ISSUE TITLE
[FR] Disable sources or profiles

### ISSUE THREAD

**Issue by costaht** [kieraneglin/pinchflat#412]
**Is your feature request related to a problem? Please describe.**
I 'd like to have the option to temporarily disable sources or profiles with the use of a slide button like the sketch below

![bitmap](https://github.com/user-attachments/assets/dc59d3c2-7e8f-4735-af75-f0e104b04bf3)

That could be useful if you're having problems with a specific channel that for example, got compromised or if you want do disable the 4K downloads (profiles) without deleting the sources

**Comment by kieraneglin** [comment]
Hey there! Thanks for the report (:

I'll think about this! Just a heads up that it'd probably only be something I'd add to sources rather than media profiles. Also, just a heads up that I'll be without cell service this week so I'll check back in on Monday 🤙

**Comment by Austin1** [comment]
Actually came here for exact same feature request. I have a profile I setup the first time I used pinchflat and wanted to delete it. I can't find a delete button or a disable button. So both of those would be good adds somewhere.

**Comment by kieraneglin** [comment]
@Austin1 You can navigate to either a Media Profile or Source and click Actions > Delete 🤙
