### ISSUE TITLE
Disk Image is Malformed

### ISSUE THREAD

**Issue by aibradford** [kieraneglin/pinchflat#414]
Ive run into this error, it appears on my source page. Its preventing me from adding/removing anything at all.

`**Status**:
`500`

**Reason**:
`%Exqlite.Error{message: "database disk image is malformed", statement: "SELECT s0.\"id\", s0.\"uuid\", s0.\"custom_name\", s0.\"description\", s0.\"collection_name\", s0.\"collection_id\", s0.\"collection_type\", s0.\"index_frequency_minutes\", s0.\"fast_index\", s0.\"use_cookies\", s0.\"download_media\", s0.\"last_indexed_at\", s0.\"download_cutoff_date\", s0.\"retention_period_days\", s0.\"original_url\", s0.\"title_filter_regex\", s0.\"output_path_template_override\", s0.\"min_duration_seconds\", s0.\"max_duration_seconds\", s0.\"series_directory\", s0.\"nfo_filepath\", s0.\"poster_filepath\", s0.\"fanart_filepath\", s0.\"banner_filepath\", s0.\"marked_for_deletion_at\", s0.\"media_profile_id\", s0.\"inserted_at\", s0.\"updated_at\", (SELECT count(sm0.\"id\") AS \"result\" FROM \"media_items\" AS sm0 WHERE (sm0.\"source_id\" = s0.\"id\") AND (NOT (sm0.\"media_filepath\" IS NULL))), (SELECT count(sm0.\"id\") AS \"result\" FROM \"media_items\" AS sm0 INNER JOIN \"sources\" AS ss1 ON ss1.\"id\" = sm0.\"source_id\" WHERE (sm0.\"source_id\" = s0.\"id\") AND (((((NOT (NOT (sm0.\"media_filepath\" IS NULL)) AND NOT (sm0.\"prevent_download\" = 1)) AND ((ss1.\"download_cutoff_date\" IS NULL) OR date(sm0.\"uploaded_at\") >= ss1.\"download_cutoff_date\")) AND   CASE\n    WHEN shorts_behaviour = 'only' AND livestream_behaviour = 'only' THEN\n      livestream = true OR short_form_content = true\n    WHEN shorts_behaviour = 'only' THEN\n      short_form_content = true\n    WHEN livestream_behaviour = 'only' THEN\n      livestream = true\n    WHEN shorts_behaviour = 'exclude' AND livestream_behaviour = 'exclude' THEN\n      short_form_content = false AND livestream = false\n    WHEN shorts_behaviour = 'exclude' THEN\n      short_form_content = false\n    WHEN livestream_behaviour = 'exclude' THEN\n      livestream = false\n    ELSE\n      true\n  END\n) AND ((ss1.\"title_filter_regex\" IS NULL) OR regexp_like(sm0.\"title\", ss1.\"title_filter_regex\"))) AND (((ss1.\"min_duration_seconds\" IS NULL) OR duration_seconds >= ss1.\"min_duration_seconds\") AND ((ss1.\"max_duration_seconds\" IS NULL) OR duration_seconds <= ss1.\"max_duration_seconds\")))), m1.\"id\", m1.\"name\", m1.\"redownload_delay_days\", m1.\"output_path_template\", m1.\"download_subs\", m1.\"download_auto_subs\", m1.\"embed_subs\", m1.\"sub_langs\", m1.\"download_thumbnail\", m1.\"embed_thumbnail\", m1.\"download_source_images\", m1.\"download_metadata\", m1.\"embed_metadata\", m1.\"download_nfo\", m1.\"sponsorblock_behaviour\", m1.\"sponsorblock_categories\", m1.\"shorts_behaviour\", m1.\"livestream_behaviour\", m1.\"preferred_resolution\", m1.\"media_container\", m1.\"marked_for_deletion_at\", m1.\"inserted_at\", m1.\"updated_at\" FROM \"sources\" AS s0 INNER JOIN \"media_profiles\" AS m1 ON m1.\"id\" = s0.\"media_profile_id\" WHERE ((s0.\"marked_for_deletion_at\" IS NULL) AND (m1.\"marked_for_deletion_at\" IS NULL)) ORDER BY s0.\"custom_name\""}`

**Stacktrace**:
```
    (ecto_sql 3.12.0) lib/ecto/adapters/sql.ex:1078: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto_sql 3.12.0) lib/ecto/adapters/sql.ex:976: Ecto.Adapters.SQL.execute/6
    (ecto 3.12.3) lib/ecto/repo/queryable.ex:232: Ecto.Repo.Queryable.execute/4
    (ecto 3.12.3) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
    (pinchflat 2024.10.2) lib/pinchflat_web/controllers/sources/source_controller.ex:44: PinchflatWeb.Sources.SourceController.index/2
    (pinchflat 2024.10.2) lib/pinchflat_web/controllers/sources/source_controller.ex:1: PinchflatWeb.Sources.SourceController.action/2
    (pinchflat 2024.10.2) lib/pinchflat_web/controllers/sources/source_controller.ex:1: PinchflatWeb.Sources.SourceController.phoenix_controller_pipeline/2
    (phoenix 1.7.14) lib/phoenix/router.ex:484: Phoenix.Router.__call__/5

```
  `

Thanks in advance for any assistance.

**Comment by kieraneglin** [comment]
Hey there! Thanks for the report (:

Unfortunately, this issue comes from the host and isn't something I can fix in-app. Sometimes it's from file corruption, sometimes it's from the app being forcefully stopped, or any number of other things.

There are a few ways to fix this. First, stop Pinchflat then install the `sqlite3` CLI on your host and check out any of these answers: https://stackoverflow.com/a/15874884/5665799

Let me know if that works! Just a heads up that I'll be out of cell service for most of this week and I'll check back on Monday

**Comment by kieraneglin** [comment]
Closing - please feel free to reopen if there's anything I can help with!
