### ISSUE TITLE
[Triage] Youtube Shorts still downloaded even if set in profile to Exclude

### ISSUE THREAD

**Issue by anarqist** [kieraneglin/pinchflat#415]
**Describe the bug**
Youtube shorts still downloading even if set to **Exclude** 

**To Reproduce**

1. Set Include Shorts to `exclude` in media profile
2. Add new source [Example 1](https://www.youtube.com/@Tronicsfix) & [Example 2](https://www.youtube.com/@sportstudiofussball)
3. Shorts are still getting downloaded
4. Example links of shorts:
[Example 1 - Short 1](https://www.youtube.com/watch?v=6hSHJH9OKm4)
[Example 1 - Short 2](https://www.youtube.com/watch?v=jwje2hTg4nU)
[Example 1 - Short 3](https://www.youtube.com/watch?v=K-OkMvMVKvM)
[Example 1 - Short 4](https://www.youtube.com/watch?v=I1VeWLJ8WEE)
^4 out of 5 downloaded videos since 2024-10-10 are shorts
[Example 2 - Short 1](https://www.youtube.com/watch?v=dQ6asDdw4YI)
[Example 2 - Short 2](https://www.youtube.com/watch?v=dorkVClLxuQ)
[Example 2 - Short 3](https://www.youtube.com/watch?v=6c_9e05O5gA)
[Example 2 - Short 4](https://www.youtube.com/watch?v=TV8bqEyOUuo)
^20 out of 33 downloaded videos since 2024-10-10 are shorts

I did not checked all individual files, but at least for the given shorts links all of them had this information stored in the Raw attributes `short_form_content: false`

**Expected behavior**
If Shorts are set to exclude they should be detected and not downloaded. 

**Diagnostic info**

- App Version: 2024.10.2
- yt-dlp Version: 2024.09.27
- Apprise Version: v1.9.0
- System Architecture: aarch64-unknown-linux-gnu
- Timezone: Europe/Berlin

- Running it on macOS 15.0.1 in Docker on M2 Max 

**Additional context**

[pinchflat-logs-2024-10-16.txt](https://github.com/user-attachments/files/17392009/pinchflat-logs-2024-10-16.txt)

**Comment by kieraneglin** [comment]
Hey there! Thanks for the report (:

I'm momentarily back in cell service but I'll be back out in the woods from tomorrow until Monday. I'll check this out then! 

My initial instinct is that there's something else going on here since there are fairly complete automated tests for this functionality, but you never know! One thing that would help is to find one of those erroneously downloaded shorts in Pinchflat, click Actions > Copy JSON, and paste that here 🤙🏻

**Comment by anarqist** [comment]
{
  "id": 9359,
  "description": "►Tools & Parts I Use (paid link): https://www.amazon.com/shop/tronicsfix
►TronicsFix Game Console Repair Forum: https://www.tronicsfixforum.com/
🎵 Like the Music? I use Epidemic Sound (paid link): http://share.epidemicsound.com/tronicsfix

SUBSCRIBE: https://www.youtube.com/channel/UCfOrKQtC1tDfGf_fFVb8pYw?sub_confirmation=1

-----------------------------------------------------------------------------------------------------------

Instagram https://www.instagram.com/tronicsfix/
Facebook https://www.facebook.com/TronicsFix/
Twitter https://twitter.com/TronicsFix
Website http://www.tronicsfix.com/

-----------------------------------------------------------------------------------------------------------

Tools I Use:
-Protech Toolkit: Amazon (paid link) https://geni.us/90il5y
-Torx Security T8: Amazon (paid link) https://geni.us/AEcBvZL
-PH00 Phillips: Amazon (paid link) https://geni.us/YGVSSv
-Tweezer Set: Amazon (paid link) https://geni.us/t0VrlcX
-Electric Screwdriver: Amazon (paid link) https://geni.us/2wbHzJ
-Thermal Paste: Amazon (paid link) https://geni.us/q2Prd
-Canned Air: Amazon (paid link) https://geni.us/CPYy

Equipment Used: 
-Hakko Hot Air Station: Amazon (paid link) https://geni.us/y2JDR
-Nozzle for hot air station: Amazon (paid link) https://geni.us/zpEWlT
-Hakko Soldering Station: Amazon (paid link) https://geni.us/MTL0qb
-Hakko Air Filter: Amazon (paid link) https://geni.us/Gqznh
-Digital Microscope: Amazon (paid link) https://geni.us/fAw8d4Q
-Stereo Microscope: Amazon (paid link) https://geni.us/WBO3b
-Kester Solder: Amazon (paid link) https://geni.us/ETXUh

→Business Inquiries Email: steve@tronicsfix.com

TronicsFix assumes no liability for property damage or injury incurred as a result of any of the information contained in this video. All material provided within this Youtube channel is for informational, educational, & entertainment purposes only. Some of these projects, materials, and techniques may not be appropriate for all ages or skill levels. No information contained in this video shall create any express or implied warranty or guarantee of any particular result.
TronicsFix does not make any claims of the safety of the projects, techniques, or resources listed on this channel and will not take responsibility of what you do with the information provided by this channel. Any injury, damage or loss that may result from improper use of these tools, equipment, or the information contained in this video is the sole responsibility of the user and not TronicsFix. Please do not attempt anything contained in this video unless you accept personal responsibility for the results, whether they are good or bad.

TronicsFix Affiliate Advertising
(*We are a participant in the Amazon Services LLC Associates Program, an affiliate advertising program designed to provide a means for us to earn fees by linking to Amazon.com and affiliated sites.)
(*We are a participant in the eBay Partner Network, an affiliate advertising program designed to provide a means for us to earn fees by linking to eBay.com.)
Disclosure of Material Connection: Some of the links in the post above are “affiliate links.” This means if you click on the link and purchase the item, I will receive an affiliate commission. Regardless, I only recommend products or services I use personally and believe will add value to my readers. I am disclosing this in accordance with the Federal Trade Commission’s 16 CFR, Part 255: “Guides Concerning the Use of Endorsements and Testimonials in Advertising.”

The music used in this video does not require attribution.",
  "title": "Trying to Repair a Dewalt Battery #tronicsfix  #diy  #dewalttools",
  "source": {
    "id": 13,
    "description": "Welcome to the TronicsFix Youtube channel! We believe that repair matters. In an age where it seems like everything is becoming less repairable we're here to show you how to fix it anyway! We think that there's no reason to throw something away if it can be fixed. On our channel, we'll show you what's inside some of the latest tech (and sometimes the old stuff too!), teach you how to fix your own stuff, and also give you an idea of what it takes to make some money on the side if that's what you're into.
We think that broken sucks and we're here to show that repair matters. So if you'd like to learn, fix, and/or earn we'd love to have you as a subscriber.

- Check out our other channel: https://www.youtube.com/@RestorishOfficial
- Learn to Solder: www.gameconsolerepairschool.com
- Ask Your Repair Questions: www.tronicsfixforum.com

Please Note: Our TronicsFix YouTube videos and posts contain Amazon and eBay affiliate links for which we may be compensated.
",
    "uuid": "b8332c0e-13e8-4914-9543-216ddf894f1f",
    "inserted_at": "2024-10-11T19:10:54Z",
    "updated_at": "2024-10-16T20:55:47Z",
    "use_cookies": false,
    "media_profile": {
      "id": 1,
      "name": "youtube",
      "inserted_at": "2024-10-04T21:45:07Z",
      "updated_at": "2024-10-10T19:04:03Z",
      "download_nfo": true,
      "output_path_template": "/shows/{{ source_custom_name }}/{{ season_by_year__episode_by_date_and_index }} - {{ title }}.{{ ext }}",
      "media_container": null,
      "preferred_resolution": "1080p",
      "sponsorblock_categories": [
        "sponsor"
      ],
      "sponsorblock_behaviour": "disabled",
      "download_thumbnail": true,
      "embed_thumbnail": true,
      "download_auto_subs": false,
      "download_subs": false,
      "embed_subs": false,
      "sub_langs": "en",
      "download_metadata": true,
      "embed_metadata": true,
      "download_source_images": true,
      "marked_for_deletion_at": null,
      "livestream_behaviour": "exclude",
      "redownload_delay_days": 1,
      "shorts_behaviour": "exclude"
    },
    "download_media": true,
    "original_url": "https://www.youtube.com/@Tronicsfix",
    "nfo_filepath": "/downloads/shows/TronicsFix/tvshow.nfo",
    "media_profile_id": 1,
    "custom_name": "TronicsFix",
    "collection_id": "UCfOrKQtC1tDfGf_fFVb8pYw",
    "collection_name": "TronicsFix",
    "collection_type": "channel",
    "fast_index": false,
    "download_cutoff_date": "2024-10-10",
    "min_duration_seconds": null,
    "max_duration_seconds": null,
    "title_filter_regex": null,
    "banner_filepath": "/downloads/shows/TronicsFix/banner.jpg",
    "fanart_filepath": "/downloads/shows/TronicsFix/fanart.jpg",
    "poster_filepath": "/downloads/shows/TronicsFix/poster.jpg",
    "series_directory": "/downloads/shows/TronicsFix",
    "index_frequency_minutes": 1440,
    "output_path_template_override": null,
    "last_indexed_at": "2024-10-16T20:55:47Z",
    "marked_for_deletion_at": null,
    "retention_period_days": 14
  },
  "uuid": "29a429a3-81d8-4751-9b65-114ae62116e2",
  "inserted_at": "2024-10-11T19:46:11Z",
  "updated_at": "2024-10-12T02:00:22Z",
  "media_id": "6hSHJH9OKm4",
  "original_url": "https://www.youtube.com/watch?v=6hSHJH9OKm4",
  "metadata_filepath": "/downloads/shows/TronicsFix/Season 2024/s2024e101099 - Trying to Repair a Dewalt Battery #tronicsfix  #diy  #dewalttools.info.json",
  "thumbnail_filepath": "/downloads/shows/TronicsFix/Season 2024/s2024e101099 - Trying to Repair a Dewalt Battery #tronicsfix  #diy  #dewalttools-thumb.jpg",
  "culled_at": null,
  "media_downloaded_at": "2024-10-12T02:00:20Z",
  "nfo_filepath": "/downloads/shows/TronicsFix/Season 2024/s2024e101099 - Trying to Repair a Dewalt Battery #tronicsfix  #diy  #dewalttools.nfo",
  "media_filepath": "/downloads/shows/TronicsFix/Season 2024/s2024e101099 - Trying to Repair a Dewalt Battery #tronicsfix  #diy  #dewalttools.mp4",
  "media_redownloaded_at": "2024-10-12T02:00:22Z",
  "media_size_bytes": 15898199,
  "prevent_download": false,
  "duration_seconds": 58,
  "livestream": false,
  "matching_search_term": null,
  "playlist_index": 0,
  "prevent_culling": false,
  "short_form_content": false,
  "source_id": 13,
  "subtitle_filepaths": [],
  "upload_date_index": 99,
  "uploaded_at": "2024-10-10T15:00:13Z"
}

Just take your time, looking forard when you are back and can investigate this deeper! Thx in advance!

**Comment by gpatkinson** [comment]
Similar problem for me. Thanks very much for the fantastic project, just what I've been looking for.

**Comment by kieraneglin** [comment]
Hey, all! I'm back from my trip and I'll be looking into this early this week. There are a few other things I have to look at first, but this is high on my priority list!

**Comment by kieraneglin** [comment]
I've replicated this issue and confirmed it's from YouTube serving a new JSON format that yt-dlp isn't equipped to handle yet. This doesn't happen for all users in all cases and I'm working on creating repeatable steps to produce this issue so the yt-dlp team can fix it.

Until then, there's nothing the app can do since this bug stops aspect ratio data from being returned which is critical for determining shorts

**Comment by gpatkinson** [comment]
Is there a maximum length of the 'Shorts' format? Although not a clean fix, maybe just add some sort of optional filter that autodeletes (or skips download) anything with duration of less than shorts.maxlength ? Might not work for everyone's use case, but I personally don't consume any normal youtube content that is less than about 5 min. 

Or maybe just wait for yt-dlp to support the new format, doesn't sound like it should be too hard to upgrade.

**Comment by kieraneglin** [comment]
You can already set a min/max length on a per-_source_ basis (you have to enable advanced mode in the upper right first, though).

The yt-dlp team is usually pretty quick to fix these things once they can reproduce the issue. I'll keep working on getting them the data they need in the meantime 🤙

**Comment by kieraneglin** [comment]
If anyone's able to help test, it would really help if you tried [updating yt-dlp](https://github.com/kieraneglin/pinchflat/wiki/Frequently-Asked-Questions#how-do-i-update-yt-dlp-independently-from-pinchflat) and letting me know if this issue persists!

I was able to replicate this issue for a short time but now I can't make it happen again so I can't confirm if the latest yt-dlp update fixes it

**Comment by anarqist** [comment]
> If anyone's able to help test, it would really help if you tried [updating yt-dlp](https://github.com/kieraneglin/pinchflat/wiki/Frequently-Asked-Questions#how-do-i-update-yt-dlp-independently-from-pinchflat) and letting me know if this issue persists!
> 
> I was able to replicate this issue for a short time but now I can't make it happen again so I can't confirm if the latest yt-dlp update fixes it

It looks like they are not downloading anymore after the manual yt-dlp update which you suggested! 🥳 Will observe this over the next couple of days to make sure it stays as it is and was not just a lucky strike. 

Thanks in the meantime!

**Comment by ryansadio** [comment]
I manually upgraded yt-dlp --version to 2024.10.22 as instructed but still seeing this issue.

Sample Media
```
{
  "id": 14540,
  "description": "All of us have over the years made efforts to become adults, it can be at once grating and dispiriting to be told that there might, nevertheless, be an ‘inner child’ still lodged somewhere within us, holding us back.

Enjoying our Youtube videos? Get full access to all our audio content, videos, and thousands of thought-provoking articles, conversation cards and more with The School of Life Subscription: https://t.ly/GVIZL 

Be more mindful, present and inspired. Get the best of The School of Life delivered straight to your inbox: https://t.ly/D7hjI

FURTHER READING

You can read more on this and other subjects here: https://bit.ly/3JFHf1M

“One of the more consistently confronting and at times embarrassing concepts that psychology forces us to consider is that of an ‘inner child.’ All of us have along the years made such efforts to become adults, it can be at once grating and dispiriting to be told that there might, nevertheless, be an ‘inner child’ still lodged somewhere within us.
But in truth, we contain within ourselves a version of all the people we have ever been. There is, in recessive form, somewhere in the folds of our natures, a confused teenager, a sad child, a jealous or hungry infant. No version of us entirely disappears, it is merely added to and buttressed, just like an oak tree that still contains, in its rings, the marks of all its former circumferences…”

MORE SCHOOL OF LIFE

Watch more films on SELF in our playlist: 
http://bit.ly/TSOLself

SOCIAL MEDIA

Feel free to follow us at the links below:

Facebook: https://www.facebook.com/theschooloflifelondon/  

X: https://twitter.com/TheSchoolOfLife   

Instagram: https://www.instagram.com/theschooloflifelondon/ 

LinkedIn: ttps://www.linkedin.com/company/the-school-of-life-for-business/

CREDITS

Produced in collaboration with:

Deanca Renysata 
https://www.youtube.com/watch?v=yNIAeV1uBPI

Title animation produced in collaboration with

Vale Productions
https://www.valeproductions.co.uk/",
  "title": "Reparenting our Inner child  #animation #theschooloflife #parenting",
  "source": {
    "id": 28,
    "description": "Self-understanding, calm and emotional maturity.

All our content is available on our app and website: www.theschooloflife.com

We offer online psychotherapy: www.theschooloflife.com/therapy

We publish one film a week, on Wednesdays at 14.00hrs GMT.",
    "uuid": "5f7299e5-679c-4f91-8846-761faacbdfc2",
    "inserted_at": "2024-10-25T17:29:43Z",
    "updated_at": "2024-10-25T18:09:47Z",
    "media_profile": {
      "id": 1,
      "name": "Web Series",
      "inserted_at": "2024-10-18T20:57:17Z",
      "updated_at": "2024-10-18T20:57:17Z",
      "output_path_template": "/{{ source_custom_name }}/{{ season_by_year__episode_by_date_and_index }} - {{ title }}.{{ ext }}",
      "media_container": null,
      "preferred_resolution": "2160p",
      "sponsorblock_categories": [
        "sponsor"
      ],
      "sponsorblock_behaviour": "remove",
      "download_thumbnail": true,
      "embed_thumbnail": true,
      "download_auto_subs": false,
      "download_subs": true,
      "embed_subs": true,
      "sub_langs": "en",
      "download_metadata": false,
      "embed_metadata": true,
      "download_nfo": true,
      "download_source_images": true,
      "livestream_behaviour": "exclude",
      "marked_for_deletion_at": null,
      "redownload_delay_days": 1,
      "shorts_behaviour": "exclude"
    },
    "nfo_filepath": "/downloads/The School of Life/tvshow.nfo",
    "original_url": "https://www.youtube.com/@theschooloflifetv",
    "media_profile_id": 1,
    "custom_name": "The School of Life",
    "collection_id": "UC7IcJI8PUf5Z3zKxnZvTBog",
    "collection_name": "The School of Life",
    "collection_type": "channel",
    "fast_index": true,
    "download_media": true,
    "use_cookies": false,
    "poster_filepath": "/downloads/The School of Life/poster.jpg",
    "fanart_filepath": "/downloads/The School of Life/fanart.jpg",
    "banner_filepath": "/downloads/The School of Life/banner.jpg",
    "marked_for_deletion_at": null,
    "download_cutoff_date": "2024-10-01",
    "min_duration_seconds": null,
    "max_duration_seconds": null,
    "title_filter_regex": null,
    "last_indexed_at": "2024-10-25T18:09:47Z",
    "index_frequency_minutes": 43200,
    "output_path_template_override": null,
    "retention_period_days": null,
    "series_directory": "/downloads/The School of Life"
  },
  "uuid": "485f2902-ab61-4084-a3fb-30e5c23b081a",
  "inserted_at": "2024-10-25T18:09:03Z",
  "updated_at": "2024-10-25T18:09:14Z",
  "source_id": 28,
  "matching_search_term": null,
  "subtitle_filepaths": [],
  "culled_at": null,
  "duration_seconds": 54,
  "livestream": false,
  "media_downloaded_at": "2024-10-25T18:09:09Z",
  "media_filepath": "/downloads/The School of Life/Season 2024/s2024e101999 - Reparenting our Inner child  #animation #theschooloflife #parenting.mp4",
  "media_id": "E1pAjzbArPY",
  "media_redownloaded_at": null,
  "media_size_bytes": 4329325,
  "metadata_filepath": null,
  "nfo_filepath": "/downloads/The School of Life/Season 2024/s2024e101999 - Reparenting our Inner child  #animation #theschooloflife #parenting.nfo",
  "original_url": "https://www.youtube.com/watch?v=E1pAjzbArPY",
  "playlist_index": 0,
  "prevent_culling": false,
  "prevent_download": false,
  "short_form_content": false,
  "thumbnail_filepath": "/downloads/The School of Life/Season 2024/s2024e101999 - Reparenting our Inner child  #animation #theschooloflife #parenting-thumb.jpg",
  "upload_date_index": 99,
  "uploaded_at": "2024-10-19T13:00:25Z"
}
```

In addition, previously downloaded Shorts are not being removed:
```
{
  "id": 919,
  "description": "JOIN MY NEWSLETTER:
https://www.damilee.com/pages/newsletter

MY FAVOURITE TOOLS:
My Youtube Camera Gear: https://kit.co/damilee/my-filming-kit
My Studio Essentials: https://kit.co/damilee/dami-s-studio-essentials
Book Recommendations: https://www.damilee.com/book-recommendations

INSTAGRAM - https://www.instagram.com/damileearch
TWITTER - https://twitter.com/damileearch
LINKEDIN (plz send me a msg first!) - https://www.linkedin.com/in/damilee

WHO AM I:
I'm Dami, a licensed Architect living in Vancouver, BC. I make videos about architecture, career, and creativity. 

WEBSITE - https://www.damilee.com

GET IN TOUCH:
If you’d like to talk, I’d love to hear from you! Commenting on a video or tweeting @damileearch will be the quickest way to get a response from me, but if your question is very long, feel free to email me at hello@damilee.com. I try my best to respond to the emails, but unfortunately, there just aren't enough hours in the day!",
  "title": "How this manga twists human symbols",
  "source": {
    "id": 4,
    "description": "Architecture and design with Dami

",
    "uuid": "56e0cc63-d47c-4582-b80c-ffa4a7b64913",
    "inserted_at": "2024-10-18T21:56:57Z",
    "updated_at": "2024-10-24T18:40:03Z",
    "media_profile": {
      "id": 1,
      "name": "Web Series",
      "inserted_at": "2024-10-18T20:57:17Z",
      "updated_at": "2024-10-18T20:57:17Z",
      "output_path_template": "/{{ source_custom_name }}/{{ season_by_year__episode_by_date_and_index }} - {{ title }}.{{ ext }}",
      "media_container": null,
      "preferred_resolution": "2160p",
      "sponsorblock_categories": [
        "sponsor"
      ],
      "sponsorblock_behaviour": "remove",
      "download_thumbnail": true,
      "embed_thumbnail": true,
      "download_auto_subs": false,
      "download_subs": true,
      "embed_subs": true,
      "sub_langs": "en",
      "download_metadata": false,
      "embed_metadata": true,
      "download_nfo": true,
      "download_source_images": true,
      "livestream_behaviour": "exclude",
      "marked_for_deletion_at": null,
      "redownload_delay_days": 1,
      "shorts_behaviour": "exclude"
    },
    "nfo_filepath": "/downloads/DamiLee/tvshow.nfo",
    "original_url": "https://www.youtube.com/@DamiLeeArch",
    "media_profile_id": 1,
    "custom_name": "DamiLee",
    "collection_id": "UCJ_2hNMxOzNjviJBiLWHMqg",
    "collection_name": "DamiLee",
    "collection_type": "channel",
    "fast_index": true,
    "download_media": true,
    "use_cookies": false,
    "poster_filepath": "/downloads/DamiLee/poster.jpg",
    "fanart_filepath": "/downloads/DamiLee/fanart.jpg",
    "banner_filepath": "/downloads/DamiLee/banner.jpg",
    "marked_for_deletion_at": null,
    "download_cutoff_date": null,
    "min_duration_seconds": null,
    "max_duration_seconds": null,
    "title_filter_regex": null,
    "last_indexed_at": "2024-10-24T18:40:03Z",
    "index_frequency_minutes": 43200,
    "output_path_template_override": null,
    "retention_period_days": null,
    "series_directory": "/downloads/DamiLee"
  },
  "uuid": "d2abdaa5-11ed-45f9-803f-b31d3dfee997",
  "inserted_at": "2024-10-18T22:02:45Z",
  "updated_at": "2024-10-19T03:50:18Z",
  "source_id": 4,
  "matching_search_term": null,
  "subtitle_filepaths": [],
  "culled_at": null,
  "duration_seconds": 50,
  "livestream": false,
  "media_downloaded_at": "2024-10-19T03:50:14Z",
  "media_filepath": "/downloads/DamiLee/Season 2024/s2024e101499 - How this manga twists human symbols.mp4",
  "media_id": "azo60G1jTq4",
  "media_redownloaded_at": null,
  "media_size_bytes": 17900001,
  "metadata_filepath": null,
  "nfo_filepath": "/downloads/DamiLee/Season 2024/s2024e101499 - How this manga twists human symbols.nfo",
  "original_url": "https://www.youtube.com/watch?v=azo60G1jTq4",
  "playlist_index": 0,
  "prevent_culling": false,
  "prevent_download": false,
  "short_form_content": true,
  "thumbnail_filepath": "/downloads/DamiLee/Season 2024/s2024e101499 - How this manga twists human symbols-thumb.jpg",
  "upload_date_index": 99,
  "uploaded_at": "2024-10-14T15:15:21Z"
}
```

**Comment by kieraneglin** [comment]
Thanks for the additional details! I'll keep working with the yt-dlp team on this.

> In addition, previously downloaded Shorts are not being removed

That is expected. With the exception of things like retention dates, old media isn't removed when your filters change

**Comment by ryansadio** [comment]
> That is expected. With the exception of things like retention dates, old media isn't removed when your filters change
I apologize for the confusion. To clarify, the filters never changed since I initially created the Media Profile - the `Include Shorts: Exclude` had always been there, yet this configuration still downloaded a bunch of Shorts when I added the Sources. I was hoping the update would fix it?

**Comment by kieraneglin** [comment]
From the app's perspective, there is no difference in these scenarios. It's programmed to not touch existing media whatsoever except in the limited cases of removing media past its retention date.

So to know if this error truly stuck around, you'd essentially have to delete and then re-add the impacted source

**Comment by ItsNoted** [comment]
Still downloading shorts for Danny Jones on my instance even when set to exclude them.

**Comment by kieraneglin** [comment]
Thanks, all! I've confirmed that the yt-dlp team is aware of these changes YouTube is making. I'll update once I have any news on that front

**Comment by kieraneglin** [comment]
Funny enough, I used to have a system very similar to ytdl-sub's but it must've stopped working at some point. Anyway, I've made a PR reverting that logic and I'd love to have some help in testing:

1. Update your Docker config to use `ghcr.io/kieraneglin/pinchflat:short-detection-test`
2. This change is not retroactive, so delete and re-add a source that was previously downloading shorts

That's it! If anyone could help test I'd be very appreciative 🙌

**Comment by ryansadio** [comment]
With `ghcr.io/kieraneglin/pinchflat:short-detection-test`, 3/3 of my testing passed!

**Comment by kieraneglin** [comment]
My testing worked as well so I'll call that good enough for now!

**Comment by ItsNoted** [comment]
Seems to be working. Thank you! Was it something I said? Awesome!

**Comment by kieraneglin** [comment]
Hey all! Popping back in to say that I wrote some one-liners [here](https://github.com/kieraneglin/pinchflat/issues/456#issuecomment-2458420594) in case you want to delete any shorts that were downloaded during this bug. Be sure to read the caveats I posted!
