### ISSUE TITLE
[Triage] Internal Server Error (:time_zone_not_found)

### ISSUE THREAD

**Issue by mc7h** [kieraneglin/pinchflat#420]
**Describe the bug**

Media is downloading as expected. However, the following error is shown on the Home panel.

```
**Status**:
`500`

**Reason**:
`%FunctionClauseError{module: Calendar, function: :strftime, arity: 3, kind: nil, args: nil, clauses: nil}`

**Stacktrace**:
```
    (elixir 1.17.0) lib/calendar.ex:575: Calendar.strftime({:error, :time_zone_not_found}, "%Y-%m-%d %H:%M", [])
    (pinchflat 2024.10.2) lib/pinchflat_web/components/custom_components/text_components.ex:94: anonymous fn/2 in PinchflatWeb.CustomComponents.TextComponents."datetime_in_zone (overridable 1)"/1
    (phoenix_live_view 0.20.3) lib/phoenix_live_view/diff.ex:391: Phoenix.LiveView.Diff.traverse/7
    (phoenix_live_view 0.20.3) lib/phoenix_live_view/diff.ex:544: anonymous fn/4 in Phoenix.LiveView.Diff.traverse_dynamic/7
    (elixir 1.17.0) lib/enum.ex:2531: Enum."-reduce/3-lists^foldl/2-0-"/3
    (phoenix_live_view 0.20.3) lib/phoenix_live_view/diff.ex:389: Phoenix.LiveView.Diff.traverse/7
    (phoenix_live_view 0.20.3) lib/phoenix_live_view/diff.ex:571: anonymous fn/3 in Phoenix.LiveView.Diff.traverse_comprehension/5
    (elixir 1.17.0) lib/enum.ex:1829: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3

```
  
```

**To Reproduce**

1. Go to Home immediately after container starts..

**Diagnostic info**

- App Version: 2024.10.2
- yt-dlp Version: 2024.09.27
- Apprise Version: v1.9.0
- System Architecture: x86_64-pc-linux-gnu
- Timezone: 'Australia/Sydney'

**Additional context**

[pinchflat-logs-2024-10-20.txt](https://github.com/user-attachments/files/17449775/pinchflat-logs-2024-10-20.txt)

**Comment by kieraneglin** [comment]
Hey there! Thanks for the report (:

This is strange! I checked locally and the formatting for the timezone you've entered is correct according to my timezone conversion library (see attached pic).

The logs you attached don't go back far enough to record the app's boot process which is what I'm most curious about. Would you mind restarting the Docker container, encountering this error, and then attaching those logs to this issue? This may be a similar case to #237 but those updated logs will hopefully clear things up.

![Screenshot 2024-10-21 at 9 38 57 AM](https://github.com/user-attachments/assets/a45ea2e9-c101-4aec-a0d9-9dc4093967d5)

**Comment by mc7h** [comment]
Sure. Hope it helps..

[Uploading pinchflat-logs-2024-10-24-2.txt…]()

**Comment by kieraneglin** [comment]
It doesn't look like that worked! I think you submitted the comment before the upload completed

**Comment by mc7h** [comment]
My bad. You're absolutely right, I was rushing 😅

**Comment by kieraneglin** [comment]
Thank you! Unfortunately those logs didn't capture the boot process but I've been poking around anyway. I haven't been able to repro this but I have a few suspicions:

- What are the odds you're running your docker container as readonly?
- Does anything change if you set the `TZ_DATA_DIR` env var to something like `/config/extras/elixir_tz_data` and restart the container?
- Barring that, what's the output of opening a console for the Pinchflat container and running `./bin/pinchflat rpc "IO.puts(Tzdata.tzdata_version)"`

**Comment by kieraneglin** [comment]
I'm closing this issue for housekeeping. If it keeps happening, please re-open this issue or create a new one!

**Comment by mc7h** [comment]
Hey @kieraneglin sorry for the delay in getting back to you. Good news! I pulled the latest image, relaunched my compose, and the error has disappeared.
