### ISSUE TITLE
[FR] Setup with config files for startup

### ISSUE THREAD

**Issue by Robsmon** [kieraneglin/pinchflat#421]
**Is your feature request related to a problem? Please describe.**
I am doing a lot with infrastructure as code at the moment and if i restart everything all my config is lost if i do not retain the config directory. I know that is an edge case as most of the time you are not spinning up and down the deployment constantly.

**Describe the solution you'd like**
It would be nice to be able to put some init config files in the config folder that are read on startup.

**Describe alternatives you've considered**
An alternative would be using an API to put them in but there is none at the moment would be another solution but maybe a bigger one.

I am thinking about implementing this myself but i would need some time to get into the code. I think i will try it but i think opening the issue first is the right way. Maybe there is anything that prevents this feature that i could not see at the moment.

**Comment by kieraneglin** [comment]
Hey there! Thanks for the report (:

I totally get the thought, but this is such an edge case that I don't think it'd have a home in the app. That said, I think there's a workaround! Would it work to copy the entire contents of your current `config` folder to a zip file and copy+unzip that as part of your infra deployment steps?

More generally, I'd be curious to hear how you're handing this with other apps. The paradigms used by pinchflat to store state in the `/config` directory are pretty standard. There might not me an in-app backup/restore UI, but fundamentally that's very similar to just saving + restoring the `/config` directory manually
