### ISSUE TITLE
[FR] Multi-language support

### ISSUE THREAD

**Issue by Foxy-NC** [kieraneglin/pinchflat#427]
Hello,
Is there any plan to add multi-language to pinchflat's UI?

**Comment by kieraneglin** [comment]
Hey there! Thanks for the report (:

It's definitely on my wishlist, but I don't have the capacity to maintain something like that at the moment (or in the near-term foreseeable future). I understand it's not ideal, but this is something I'll have to re-assess when I've gotten some other big outstanding features/bugfixes in place
