### ISSUE TITLE
[Triage] Retention Period is off by 2 days

### ISSUE THREAD

**Issue by anarqist** [kieraneglin/pinchflat#428]
**Describe the bug**
Hi, I noticed that the amount of days set on Retention Period is off by 2 days, meaning, if Set to 3 days, Videos of the last 5 days are still available and only older than 5 are removed. If set to 7 days they are there for 9 days etc. I initially had some channels set to 7-14 days and it was the same behaviour, I then changed them last night to 3-5 days and lots of Videos were removed but still 2 days off. This is reproducible an all channels so far (only have a single digit number of sources, but it is on all of them)

**To Reproduce**

1. Set Retention Period to Amount X of days
2. Save settings
3. Download videos
4. Check the oldest one
5. it will be 2 days off the set amount of days.

**Expected behavior**
If set to 3 days, maximum on the fourth day when it indexes again or checks for new downloads it should remove the oldest one out of the timeframe. 

**Screenshots**

<img width="1435" alt="SCR-20241023-qqpb" src="https://github.com/user-attachments/assets/44ad8616-e8bf-401c-86bf-c718de7d5c36">
<img width="1464" alt="SCR-20241023-qqtv" src="https://github.com/user-attachments/assets/580cc94a-a858-4f49-bfaa-c463441e17e6">
<img width="1442" alt="SCR-20241023-qqwz" src="https://github.com/user-attachments/assets/0fc54330-38eb-48d6-ad11-f75562b76850">
<img width="1460" alt="SCR-20241023-qqzv" src="https://github.com/user-attachments/assets/59562d90-4a3a-4670-9781-8d1361be7fd4">

**Diagnostic info**

- App Version: 2024.10.2
- yt-dlp Version: 2024.09.27
- Apprise Version: v1.9.0
- System Architecture: aarch64-unknown-linux-gnu
- Timezone: Europe/Berlin

**Comment by kieraneglin** [comment]
Hey there (: Thanks for the report!

I just checked and you're right! There are a few checks that need to be updated. I'll make some changes that address this, but keep in mind that there will always be a little wiggle room with the dates since the deletion worker only runs once per day. Even after I make this fix, there may still be cases where something hangs on a _little_ longer than you may expect, but it shouldn't ever be off by more than 24h.

**Comment by anarqist** [comment]
> Hey there (: Thanks for the report!
> 
> I just checked and you're right! There are a few checks that need to be updated. I'll make some changes that address this, but keep in mind that there will always be a little wiggle room with the dates since the deletion worker only runs once per day. Even after I make this fix, there may still be cases where something hangs on a _little_ longer than you may expect, but it shouldn't ever be off by more than 24h.

Yea 24hrs delay is totally fine as I said in my initial report, because it obviously depends on timing of when was the video downloaded and when is the next check. So if it gets deleted sometime during the 4th day that is understandable!

Thanks for checking! 🫶
