### ISSUE TITLE
[FR] Change class for controls so video looks bigger

### ISSUE THREAD

**Issue by erickosanchezj** [kieraneglin/pinchflat#430]
**Is your feature request related to a problem? Please describe.**
Not so much of a problem but rather make the video bigger in the http://YOURIP/sources/#/media/### part so it looks best and information is not on the way.

**Describe the solution you'd like**
Change should be done here:
```HTML
<video controls="" class="max-h-96 w-full">
    <source src="/media/LONGGUIDHERE/stream" type="video/ext">
    Your browser does not support the video element.
  </video>
```

Where instead of 96, it shows 128 in h value:
```HTML
<video controls="" class="max-h-128 w-full">
    <source src="/media/LONGGUIDHERE/stream" type="video/ext">
    Your browser does not support the video element.
  </video>
```

Change should also be done here from 2 cols: ```<section class="grid grid-cols-1 xl:grid-cols-2 xl:gap-6 mt-6">```
to 1 col: ```<section class="grid grid-cols-1 xl:grid-cols-2 xl:gap-6 mt-6">```

This moves the video information out of the way.

**Describe alternatives you've considered**
Probably a Custom CSS part would do the trick?

**Additional context**
N/A

**Comment by kieraneglin** [comment]
Hey there! Thanks for the report (:

I think I agree! I'll look into this change 🤙 

It's important to reiterate that Pinchflat isn't really meant for consuming content in-app so certain limitations are expected (eg: you can't view MKVs in Firefox). But even knowing that, I think this change looks better anyway

**Comment by erickosanchezj** [comment]
> Hey there! Thanks for the report (:
> 
> I think I agree! I'll look into this change 🤙
> 
> It's important to reiterate that Pinchflat isn't really meant for consuming content in-app so certain limitations are expected (eg: you can't view MKVs in Firefox). But even knowing that, I think this change looks better anyway

I do agree that Pinchflat is not for watching content and I was hesitant to submit it, but I think the change did not break that much and was easier on the eyes, so thanks for taking this into account!
