### ISSUE TITLE
Folders not being created from Media Profile Output path

### ISSUE THREAD

**Issue by gnartroid** [kieraneglin/pinchflat#431]
I have 4 sources setup so I expected to see 4 folders with respecive videos in each. 

My Media Profile has the Output path template: {{ source_custom_name }}/{{ upload_yyyy_mm_dd }} - {{ title }}.{{ ext }} 

My assumption is that it should create a new folder for each source and then the videos should be named "Uploaddate - Title of Video"
The files also aren't named this way, it's not adding the date; only the title. Which is confusing since they're not in the correct folder. 

Is my template correct? Or is this a bug?

**Comment by kieraneglin** [comment]
Hey there! Thanks for the report (:

This is likely another symptom of some changes that YouTube is making behind-the-scenes. It also looks like yt-dlp has just released a new version which may address this! I'll try to get a new release up today to see if that fixes it

**Comment by kieraneglin** [comment]
I just pushed out a new release - would you mind updating and let me know if that fixes it?

**Comment by gnartroid** [comment]
Hi Kieran, 

I updated an hour after you released the update and it has fixed the problem I was having.

Thank you!

**Comment by mindpaletteco** [comment]
> I just pushed out a new release - would you mind updating and let me know if that fixes it?

Do you know when the Unraid container will be updated?  I'm having the same issue.  Many thanks - love your app!

**Comment by kieraneglin** [comment]
@mindpaletteco Unraid pulls from the same Docker registry as everything else so it should update based on your Unraid settings. If you open the app and it doesn't say version `2024.10.25` in the lower left, try manually updating the container 🤙

**Comment by mindpaletteco** [comment]
Ok - I'll give that a try.  Many thanks!
