### ISSUE TITLE
[Triage] Can't run two docker Containers: the name pinchflat@<containername> seems to be in use by another Erlang node 

### ISSUE THREAD

**Issue by ThomasHH42** [kieraneglin/pinchflat#439]
**Describe the bug**
I'm trying to run two docker instances of Pinchflat at the same time on my Synology Diskstation. Each container works fine individually, one running on the default port 8945 and one changed to 8947. But whenever I try to start the second one while the other one is already running, it would stop after a minute. Error message in the protocol is "[0mProtocol 'inet_tcp': the name pinchflat@<containername> seems to be in use by another Erlang node ", where <containername> is my selected containername. It doesn't matter which one it is, the error always comes up for the one that is started as the second instance.

**To Reproduce**

1. Create two container instances in Container Manager
2. Start both instances

**Expected behavior**
Two separate instances of Pinchflat accessable on two different ports.

**Screenshots**
-

**Diagnostic info**

Not possible, since the instance won't start.

**Additional context**

-

**Comment by kieraneglin** [comment]
Hey there! Thanks for the report (:

This is strange. I've been running multiple instances on the same network for a while without issue. I've seen this issue before and there are some Erlang/Elixir release settings I can tweak, but before I start looking into that can you confirm a few things for me?

- Do both containers have different names in Docker? You'd need to set `--name your_name` on your `docker run` command or the `name` key in your Docker Compose
- What kind of network are these containers on?

**Comment by ThomasHH42** [comment]
Hi, thanks for getting back to me

to be honest, I'm not quite sure. I've been using Synology's Container Manager so I didn't directly create a docker run or compose. It does have a "Containername" though. That's what's behind the @ in the error message. Would that be the name you're talking about? I attached the complete protocol I can see as a CSV export.
Both containers are using the host network, so they're running on the Synology NAS's IP on my standard home network.
Tried to avoid diving into the command line for docker so far as the GUI is very comfortable :-)

Thomas

[Pf-Tina.csv](https://github.com/user-attachments/files/17546009/Pf-Tina.csv)

**Comment by kieraneglin** [comment]
> Both containers are using the host network

That'd do it! Running on the host network will always cause issues if you want to run two of the same container. Could you try switching both of them to bridge networks and see if that fixes things?

In general I'd recommend instead setting up a new Docker network since that lets you do some cool things down the line with other containers, but for now setting it as a bridge should be fine

**Comment by ThomasHH42** [comment]
OK, that worked. Looks like I misunderstood how docker works. Life is constant learning :-)
Thanks for helping me out!

**Comment by kieraneglin** [comment]
> Life is constant learning

It is if you're doing it right, anyway! Thanks for following up 🤙🏻
