### ISSUE TITLE
[Triage] Internal Server Error After Setup

### ISSUE THREAD

**Issue by crchambers** [kieraneglin/pinchflat#440]
**Describe the bug**
Upon completing the setup process I am met with the error shown below on the home screen. The backend appears to still be working as the youtube channel I had setup to download is indeed downloading. I tried using a previous release to see if it was potentially an error with this release and I encountered the same issue. Any insight you can provide into this would be much appreciated!

**To Reproduce**

1. Pulled docker image using docker compose
2. went through the setup process where I checked every box
- Checked subtitles
- Checked All Metadata
- Checked all Cover image options
- Checked all NFO options
3. Added a youtube channel as a source. The source only has livestreams.
4. Went to home page and home page displayed error.

Pulled docker image

**Expected behavior**

**Screenshots**

![image](https://github.com/user-attachments/assets/00f28a57-b61f-44e6-80ea-f7e2f28a0a5e)

**Diagnostic info**

**Status**:
`500`

**Reason**:
`%FunctionClauseError{module: Calendar, function: :strftime, arity: 3, kind: nil, args: nil, clauses: nil}`

**Stacktrace**:
```
    (elixir 1.17.0) lib/calendar.ex:575: Calendar.strftime({:error, :time_zone_not_found}, "%Y-%m-%d %H:%M", [])
    (pinchflat 2024.10.25) lib/pinchflat_web/components/custom_components/text_components.ex:101: anonymous fn/2 in PinchflatWeb.CustomComponents.TextComponents."datetime_in_zone (overridable 1)"/1
    (phoenix_live_view 0.20.3) lib/phoenix_live_view/diff.ex:391: Phoenix.LiveView.Diff.traverse/7
    (phoenix_live_view 0.20.3) lib/phoenix_live_view/diff.ex:544: anonymous fn/4 in Phoenix.LiveView.Diff.traverse_dynamic/7
    (elixir 1.17.0) lib/enum.ex:2531: Enum."-reduce/3-lists^foldl/2-0-"/3
    (phoenix_live_view 0.20.3) lib/phoenix_live_view/diff.ex:389: Phoenix.LiveView.Diff.traverse/7
    (phoenix_live_view 0.20.3) lib/phoenix_live_view/diff.ex:571: anonymous fn/3 in Phoenix.LiveView.Diff.traverse_comprehension/5
    (elixir 1.17.0) lib/enum.ex:1829: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3

```
  

- App Version: 2024.10.2
- yt-dlp Version: 2024.09.27
- Apprise Version: v1.9.0
- System Architecture: x86_64-pc-linux-gnu
- Timezone: america/chicago

**Comment by kieraneglin** [comment]
Hey there! Thanks for the report (:

Try setting the timezone as `America/Chicago` instead of `america/chicago` and let me know if that works 🤙

**Comment by crchambers** [comment]
Yes this fixed my issue! Thanks
