### ISSUE TITLE
[FR] Import YouTube subscriptions List 

### ISSUE THREAD

**Issue by PaulEins** [kieraneglin/pinchflat#446]
Can you make YT import list?
<img width="824" alt="Bildschirmfoto 2024-10-30 um 15 12 50" src="https://github.com/user-attachments/assets/56fe783f-042b-46c8-8b04-90d104eadc2a">

**Comment by kieraneglin** [comment]
Hey there! Thanks for the report (:

Due to the complexity in setting up a new Source, I don't think a CSV import would be the right tool for the job here. But issue #435 goes over potentially setting up an API which would allow for stuff like this. Keep an eye on that one!
