### ISSUE TITLE
[FR] Allow yt-dlp plugins (incl. dearrow)

### ISSUE THREAD

**Issue by AeliusSaionji** [kieraneglin/pinchflat#448]
Dearrow is a repository of user contributed titles and thumbnails. The goal is to provide descriptive alternatives to clickbait.

You can read up on dearrow from the site:
https://dearrow.ajay.app/

There is a yt-dlp plugin that can fetch titles, but apparently not thumbnails:
https://github.com/QuantumWarpCode/yt-dlp-dearrow

I suppose if we disregard thumbnail support, there doesn't really need to be an "option" for titles, as it can be requested (or not) by an output template like  `{{ dearrow_title }}`.
 
Pinchflat may still want to record the original video title, so it may be found by pinchflat search.

Thanks!

**Comment by kieraneglin** [comment]
Hey there! Thanks for the report (:

I don't expect I'll add support for this plugin _specifically_, but instead I'll use this as a prompt to look into ways for users to add arbitrary plugins if they want.

**Comment by kieraneglin** [comment]
Done! This will be going up in the next release 🤙 

Once that release is out, you can follow the docs [here](https://github.com/kieraneglin/pinchflat/wiki/%5BAdvanced%5D-yt%E2%80%90dlp-plugins) to install plugins. You can then read the [docs for custom yt-dlp options](https://github.com/kieraneglin/pinchflat/wiki/%5BAdvanced%5D-Custom-yt%E2%80%90dlp-options) and add `--use-postprocessor DeArrow:when=pre_process` to `base-config.txt`
