### ISSUE TITLE
[FR] Export OPML for podcast app import

### ISSUE THREAD

**Issue by dozerman-ms** [kieraneglin/pinchflat#449]
**Describe the solution you'd like**
Export OPML file that points to Pinchflat source RSS feeds, allowing a podcast app to ingest all collected Pinchflat feeds. 

**Describe alternatives you've considered**
Individually adding each RSS feed by copying and pasting the URL of each one to my podcast app.

**Comment by kieraneglin** [comment]
Hey there! Thanks for the report (:

This is a good idea! I'll be blunt by saying it's a lower priority than some of the other things I'm working on right now, but I'll keep this open to track this feature going forward

**Comment by dozerman-ms** [comment]
In a stroke of serendipity, I started learning Elixir about a week ago. Just noticed PF is Elixir when I cloned the repo. I may make a PR later once I have a grip on things, assuming quality is up to par and everyone is okay with it. Looking to see how much effort it may take to get to that goal.

**Comment by dozerman-ms** [comment]
Hey [lamarios](https://github.com/lamarios). I've been having trouble getting things set up. If you're waiting to act because of me, just know it's going to be awhile.

**Comment by kieraneglin** [comment]
Let me know if there's anything I can help with!

**Comment by dozerman-ms** [comment]
I just re-tried. I was being dumb and didn't have docker-compose installed. 

Where does pinchflat store the source's metadata? Is it config/db/pinchflat.db? Is that sqllite?

**Comment by kieraneglin** [comment]
That's all correct. Metadata for user consumption is stored on the sources table, metadata for the app's internal use is stored on the source_metadata table. Prefer to use the former unless there's a really good reason to use the latter

**Comment by dozerman-ms** [comment]
Sorry for bothering you again. Looks like I'm barking up the wrong tree. 

When the clicks "copy rss feed" where is that data stored?

**Comment by dozerman-ms** [comment]
For future reference, the information that I was looking for was the "uuid" column in the "sources" table. This table should hold everything I need to build the OPML file's data.

**Comment by dozerman-ms** [comment]
I see in 'router.ex' that there is no shortage of endpoints. Is there an endpoint to get all UUIDs? I couldn't find anything that seemed to be. If not, how might I go about creating an endpoint to get (maybe json) of all source UUIDs?
