### ISSUE TITLE
Why do some files not appear in Plex after downloading?

### ISSUE THREAD

**Issue by trijste** [kieraneglin/pinchflat#452]
I'm stoked to have this up and running. I figured out I needed to update the output path template to have the "episodes" appear in seasons, etc. I found and followed this in a reddit thread:

- Create or update a media profile and ensure it creates folders for each season of a show. Enable the NFO/Series Images settings at the bottom of the form.
- Use the Media Center preset.
- The recommended output path template to create the directory structure that apps need is as follows: `/{{ source_custom_name }}/Season {{ season_from_date }}/{{ season_episode_from_date }} - {{ title }}.{{ ext }}`
- In Plex (or a similar application), add the directory containing the newly downloaded media to your TV Shows collection. Enable "Prefer Local Metadata" and "Use Local Assets."

This works for everything so far, except one source. I've downloaded 7 files but only one of them appears in Plex. Why do some files not appear in Plex after downloading? Is there some technique to fool proof this?

**Comment by kieraneglin** [comment]
Hey there! Thanks for the report (:

If this is still happening, I need some more details to best troubleshoot this. In Pinchflat, could you navigate to the one media item of the seven that _does_ show up and click Actions > Copy JSON and post that here? Could you then also do the same thing for one of the other media items that _doesn't_ show up in Plex? Essentially, I want to compare the output and see if it's something to do with the naming scheme or if it's something to do with Plex

**Comment by trijste** [comment]
(I apologize that these examples happen to be late-night American politics videos :( )

**Here's the one that I see in Plex:**

{
  "id": 2943,
  "description": "All the news and jokes you missed from the week of October 28.\n\nLate Night with Seth Meyers. Stream now on Peacock: https://bit.ly/3erP2gX\n\nSubscribe to Late Night: http://bit.ly/LateNightSeth\n \nWatch Late Night with Seth Meyers Weeknights 12:35ET/11:35c on NBC.\n \nGet more Late Night with Seth Meyers: http://www.nbc.com/late-night-with-seth-meyers/\n \nLATE NIGHT ON SOCIAL\nFollow Late Night on Twitter: https://twitter.com/LateNightSeth\nLike Late Night on Facebook: https://www.facebook.com/LateNightSeth\nFollow Late Night Instagram: http://instagram.com/LateNightSeth\nLate Night on Tumblr: http://latenightseth.tumblr.com/\n \nLate Night with Seth Meyers on YouTube features A-list celebrity guests, memorable comedy, and topical monologue jokes.\n \nGET MORE NBC\nLike NBC: http://Facebook.com/NBC\nFollow NBC: http://Twitter.com/NBC\nNBC Tumblr: http://NBCtv.tumblr.com/\nYouTube: http://www.youtube.com/nbc\nNBC Instagram: http://instagram.com/nbc\n \nTrump's MSG Rally, Biden Calls Trump Supporters Garbage: Late Night's News of the Week\nhttps://youtu.be/FfcxTvbVnBc\n\nLate Night with Seth Meyers\nhttp://www.youtube.com/user/latenightseth",
  "title": "Trump's MSG Rally, Biden Calls Trump Supporters Garbage: Late Night's News of the Week",
  "source": {
    "id": 7,
    "description": "Beloved \"Saturday Night Live\" personality — and the longest serving anchor on the show's wildly popular \"Weekend Update\" — Seth Meyers takes over as host of NBC's \"Late Night,\" home to A-list celebrity guests, memorable comedy and the best in musical talent. \n\nWatch Late Night with Seth Meyers weeknights 12:35/11:35c.\n\nLate Night with Seth Meyers is available now on Peacock, the new streaming service from NBCUniversal.  Watch thousands of hours of hit movies and shows, plus daily news, sports, and pop culture updates.  Stream now on Peacock: https://bit.ly/2OlOJcW",
    "uuid": "8f4c3b06-78f3-48b8-8321-458ee006c4d5",
    "inserted_at": "2024-11-03T00:18:06Z",
    "updated_at": "2024-11-03T04:24:08Z",
    "media_profile": {
      "id": 1,
      "name": "Plex",
      "inserted_at": "2024-11-02T16:25:08Z",
      "updated_at": "2024-11-02T17:29:59Z",
      "output_path_template": "/{{ source_custom_name }}/Season {{ season_from_date }}/{{ season_episode_from_date }} - {{ title }}.{{ ext }}",
      "media_container": null,
      "preferred_resolution": "1080p",
      "sponsorblock_categories": [
        "sponsor"
      ],
      "sponsorblock_behaviour": "remove",
      "download_thumbnail": false,
      "embed_thumbnail": false,
      "download_auto_subs": false,
      "download_subs": false,
      "embed_subs": false,
      "sub_langs": "en",
      "download_metadata": true,
      "embed_metadata": true,
      "download_nfo": true,
      "download_source_images": true,
      "livestream_behaviour": "exclude",
      "marked_for_deletion_at": null,
      "redownload_delay_days": null,
      "shorts_behaviour": "exclude"
    },
    "nfo_filepath": "/downloads/LateNightSeth/tvshow.nfo",
    "original_url": "https://www.youtube.com/@LateNightSeth",
    "media_profile_id": 1,
    "custom_name": "LateNightSeth",
    "collection_id": "UCVTyTA7-g9nopHeHbeuvpRA",
    "collection_name": "Late Night with Seth Meyers",
    "collection_type": "channel",
    "download_media": true,
    "use_cookies": false,
    "fast_index": true,
    "marked_for_deletion_at": null,
    "index_frequency_minutes": 43200,
    "output_path_template_override": null,
    "banner_filepath": "/downloads/LateNightSeth/banner.jpg",
    "download_cutoff_date": "2024-11-01",
    "fanart_filepath": "/downloads/LateNightSeth/fanart.jpg",
    "last_indexed_at": "2024-11-03T04:24:08Z",
    "max_duration_seconds": null,
    "min_duration_seconds": null,
    "poster_filepath": "/downloads/LateNightSeth/poster.jpg",
    "retention_period_days": 5,
    "series_directory": "/downloads/LateNightSeth",
    "title_filter_regex": null
  },
  "uuid": "af01ec7b-14a4-44f3-b312-510eedfd59cb",
  "inserted_at": "2024-11-03T00:19:46Z",
  "updated_at": "2024-11-03T00:20:28Z",
  "culled_at": null,
  "duration_seconds": 643,
  "livestream": false,
  "matching_search_term": null,
  "media_downloaded_at": "2024-11-03T00:20:20Z",
  "media_filepath": "/downloads/LateNightSeth/Season 2024/s2024e1101 - Trump's MSG Rally, Biden Calls Trump Supporters Garbage： Late Night's News of the Week.mp4",
  "media_id": "FfcxTvbVnBc",
  "media_redownloaded_at": null,
  "media_size_bytes": 86472860,
  "metadata_filepath": "/downloads/LateNightSeth/Season 2024/s2024e1101 - Trump's MSG Rally, Biden Calls Trump Supporters Garbage： Late Night's News of the Week.info.json",
  "nfo_filepath": "/downloads/LateNightSeth/Season 2024/s2024e1101 - Trump's MSG Rally, Biden Calls Trump Supporters Garbage： Late Night's News of the Week.nfo",
  "original_url": "https://www.youtube.com/watch?v=FfcxTvbVnBc",
  "playlist_index": 1,
  "prevent_culling": false,
  "prevent_download": false,
  "short_form_content": false,
  "source_id": 7,
  "subtitle_filepaths": [],
  "thumbnail_filepath": null,
  "upload_date_index": 99,
  "uploaded_at": "2024-11-01T19:54:46Z"
}

**Here's an example of one that has downloaded to the same location, but I don't see it in Plex:**

{
  "id": 2944,
  "description": "Mika Brzezinski talks about telling the stories of women not being able to get life-saving healthcare under Trump's abortion ban, Trump's America being an issue that impacts both women and men and the importance of this election.\n\nLate Night with Seth Meyers.  Stream now on Peacock: https://bit.ly/3erP2gX\n\nSubscribe to Late Night: http://bit.ly/LateNightSeth\n \nWatch Late Night with Seth Meyers Weeknights 12:35ET/11:35c on NBC.\n \nGet more Late Night with Seth Meyers: http://www.nbc.com/late-night-with-seth-meyers/\n \nLATE NIGHT ON SOCIAL\nFollow Late Night on Twitter: https://twitter.com/LateNightSeth\nLike Late Night on Facebook: https://www.facebook.com/LateNightSeth\nFollow Late Night Instagram: http://instagram.com/LateNightSeth\nLate Night on Tumblr: http://latenightseth.tumblr.com/\n \nLate Night with Seth Meyers on YouTube features A-list celebrity guests, memorable comedy, and topical monologue jokes.\n \nGET MORE NBC\nLike NBC: http://Facebook.com/NBC\nFollow NBC: http://Twitter.com/NBC\nNBC Tumblr: http://NBCtv.tumblr.com/\nYouTube: http://www.youtube.com/nbc\nNBC Instagram: http://instagram.com/nbc\n \nMika Brzezinski on the Horrific Impact of Trump's Abortion Ban, Fascist Comments and the Election - Late Night with Seth Meyers\nhttps://youtu.be/PXBhqjWm6DM\n\nLate Night with Seth Meyers\nhttp://www.youtube.com/user/latenightseth",
  "title": "Mika Brzezinski on the Horrific Impact of Trump's Abortion Ban, Fascist Comments and the Election",
  "source": {
    "id": 7,
    "description": "Beloved \"Saturday Night Live\" personality — and the longest serving anchor on the show's wildly popular \"Weekend Update\" — Seth Meyers takes over as host of NBC's \"Late Night,\" home to A-list celebrity guests, memorable comedy and the best in musical talent. \n\nWatch Late Night with Seth Meyers weeknights 12:35/11:35c.\n\nLate Night with Seth Meyers is available now on Peacock, the new streaming service from NBCUniversal.  Watch thousands of hours of hit movies and shows, plus daily news, sports, and pop culture updates.  Stream now on Peacock: https://bit.ly/2OlOJcW",
    "uuid": "8f4c3b06-78f3-48b8-8321-458ee006c4d5",
    "inserted_at": "2024-11-03T00:18:06Z",
    "updated_at": "2024-11-03T04:24:08Z",
    "media_profile": {
      "id": 1,
      "name": "Plex",
      "inserted_at": "2024-11-02T16:25:08Z",
      "updated_at": "2024-11-02T17:29:59Z",
      "output_path_template": "/{{ source_custom_name }}/Season {{ season_from_date }}/{{ season_episode_from_date }} - {{ title }}.{{ ext }}",
      "media_container": null,
      "preferred_resolution": "1080p",
      "sponsorblock_categories": [
        "sponsor"
      ],
      "sponsorblock_behaviour": "remove",
      "download_thumbnail": false,
      "embed_thumbnail": false,
      "download_auto_subs": false,
      "download_subs": false,
      "embed_subs": false,
      "sub_langs": "en",
      "download_metadata": true,
      "embed_metadata": true,
      "download_nfo": true,
      "download_source_images": true,
      "livestream_behaviour": "exclude",
      "marked_for_deletion_at": null,
      "redownload_delay_days": null,
      "shorts_behaviour": "exclude"
    },
    "nfo_filepath": "/downloads/LateNightSeth/tvshow.nfo",
    "original_url": "https://www.youtube.com/@LateNightSeth",
    "media_profile_id": 1,
    "custom_name": "LateNightSeth",
    "collection_id": "UCVTyTA7-g9nopHeHbeuvpRA",
    "collection_name": "Late Night with Seth Meyers",
    "collection_type": "channel",
    "download_media": true,
    "use_cookies": false,
    "fast_index": true,
    "marked_for_deletion_at": null,
    "index_frequency_minutes": 43200,
    "output_path_template_override": null,
    "banner_filepath": "/downloads/LateNightSeth/banner.jpg",
    "download_cutoff_date": "2024-11-01",
    "fanart_filepath": "/downloads/LateNightSeth/fanart.jpg",
    "last_indexed_at": "2024-11-03T04:24:08Z",
    "max_duration_seconds": null,
    "min_duration_seconds": null,
    "poster_filepath": "/downloads/LateNightSeth/poster.jpg",
    "retention_period_days": 5,
    "series_directory": "/downloads/LateNightSeth",
    "title_filter_regex": null
  },
  "uuid": "ac23594d-6a63-4439-bb38-8f475814a931",
  "inserted_at": "2024-11-03T00:19:50Z",
  "updated_at": "2024-11-03T00:20:38Z",
  "culled_at": null,
  "duration_seconds": 632,
  "livestream": false,
  "matching_search_term": null,
  "media_downloaded_at": "2024-11-03T00:20:31Z",
  "media_filepath": "/downloads/LateNightSeth/Season 2024/s2024e1101 - Mika Brzezinski on the Horrific Impact of Trump's Abortion Ban, Fascist Comments and the Election.mp4",
  "media_id": "PXBhqjWm6DM",
  "media_redownloaded_at": null,
  "media_size_bytes": 101056458,
  "metadata_filepath": "/downloads/LateNightSeth/Season 2024/s2024e1101 - Mika Brzezinski on the Horrific Impact of Trump's Abortion Ban, Fascist Comments and the Election.info.json",
  "nfo_filepath": "/downloads/LateNightSeth/Season 2024/s2024e1101 - Mika Brzezinski on the Horrific Impact of Trump's Abortion Ban, Fascist Comments and the Election.nfo",
  "original_url": "https://www.youtube.com/watch?v=PXBhqjWm6DM",
  "playlist_index": 2,
  "prevent_culling": false,
  "prevent_download": false,
  "short_form_content": false,
  "source_id": 7,
  "subtitle_filepaths": [],
  "thumbnail_filepath": null,
  "upload_date_index": 98,
  "uploaded_at": "2024-11-01T11:00:28Z"
}

**Comment by trijste** [comment]
Following up to confirm that there is an issue with the naming pattern. I renamed the files to clearly indicate S**E**, and they appeared. Therefore, I need to adjust the naming convention somehow.

**Comment by trijste** [comment]
Ok, I see I can also change the output format by source. I'm happy to play with this, but can you please tell me if there's an option to update/rename all files already downloaded based on an update to the output format?

**Comment by kieraneglin** [comment]
> [is there] an option to update/rename all files already downloaded based on an update to the output format?

There isn't currently, but this is something I've been wanting to add for a while since it makes a lot of sense as a feature. At the moment I don't have a better solution than to recommend deleting the files and re-downloading them. But keep an eye out for when I eventually add the ability to rename!

If it makes deletion any easier, instead of deleting the files through the app you can instead delete them using your OS's file manager then go to the source and use Actions > Sync Files On Disk. This will tell Pinchflat to update its records of whether a file exists or not

**Comment by kieraneglin** [comment]
Just FYI that issue #408 is tracking the renaming feature

**Comment by Kribensisis** [comment]
Hi. Sorry to comment on a closed issue, but I'm having the same problem and not following the workaround @trijste used. Basically, some playlists show up fine in Plex and some are incomplete, even though the files are downloaded. 

The ones that don't show up have multiple files in a single folder like the below, but if I renumber their `episode` and move it to a new folder titled after the episode name, they appear. 

<img width="711" alt="Image" src="https://github.com/user-attachments/assets/1419296d-1c8a-4ddb-b798-2ff2d48bb016" />

I think this is a problem with the output path variables I'm using, but I can't figure those out. 

`/{{ source_custom_name }}/{{ static_season__episode_by_date }}/{{ title }} [{{ id }}].{{ ext }}` sometimes works, and 
`output_path_template: 
/{{ source_custom_name }}/{{ static_season__episode_by_date }}/{{ title }} [{{ id }}].{{ ext }}` also does, but there's no one set of variables that alway works. And usually, none do. 

Any thoughts?
