### ISSUE TITLE
[FR] `media_filepath` Visible in Media Page When Indexed (but not downloaded)

### ISSUE THREAD

**Issue by Shackelford-Arden** [kieraneglin/pinchflat#453]
**Is your feature request related to a problem? Please describe.**

When validating the configuration for a Source, it's difficult to visualize what the final folder structure will be for the media, when finally downloaded.

**Describe the solution you'd like**

When viewing a media's page in Pinchflat (for example: `/sources/5/media/3186#tab-media`), it would be helpful to be able to see the `media_filepath` _even if the file has not been download_. To me, the use case here would be when one is validating sources before toggling the `Download Media` option, especially when dealing w/ regex filtering :smile: .

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by kieraneglin** [comment]
Hey there! Thanks for the suggestion (:

I definitely see the value here! I would need to store this as a field with a different name than the existing `media_filepath` field, but that's a small change.

I'm not sure when I'll be able to implement this, but I'll look into it and see what I can find!

**Comment by Shackelford-Arden** [comment]
That's what I'm looking for. Thank you! 😎
