### ISSUE TITLE
Support for multiple drives?

### ISSUE THREAD

**Issue by memaxwelll** [kieraneglin/pinchflat#457]
Hey there!
Loving this project so far.

One thing I could not figure out so far was whether one is able to add multiple drives?

**Comment by kieraneglin** [comment]
Hey there! Thanks for the report (:

This isn't explicit support for multiple drives in-app, but you should be able to get something like that by setting up some symlinks on your host OS. 

You may also be able to use Docker volume mounts to accomplish this, but I haven't tried that. For instance, maybe you could map `/disk_1/youtube` on the host to `/downloads/disk_1` on the container and same with a hypothetical `disk_2`. Then, when setting up your Media Profiles you could set the output template to something like `/disk_2/{{ title }}.{{ ext }}`. Again, all untested and I'm mostly just thinking out loud

**Comment by memaxwelll** [comment]
Thanks for the feedback!
I will try asap and get back to yo about how it went :)

I am sure I am not the only one with a rapidly growing library :)

**Comment by memaxwelll** [comment]
Short update!

In my stack I have defined as this:
`
/mnt/6TB_1/YT:/downloads/6TB1
`
In the Media Profiles as this:
`/6TB1/%(uploader)s - NA - %(uploader)s_-_Videos [%(channel_id)s]/%(uploader)s - %(upload_date>%Y%m%d)s - %(title)s[%(id)s].%(ext)s`

At least on one drive this seems to be working flawlessly so I would expect it to be working as soon as I add sources to the second profile.

_BTW:_
I have succesfully transferred the pinchflat config from one OS to another
It might seem obvious to users but I had sweaty palms and had to figure out that one can just copy the pinchflat folder and make sure to update the stack if the path changes.
