### ISSUE TITLE
[FR] Add a way to create a new media profile based on an existing one

### ISSUE THREAD

**Issue by spv-1** [kieraneglin/pinchflat#459]
**Is your feature request related to a problem? Please describe.**

Sometimes I want to make a new media profile, but based on one I've already created (e.g., maybe I want all the settings to be the same as another profile I created, only changing the preferred resolution). As far as I can tell, I have to manually fill out each item in the new profile based on the old one to do that.

**Describe the solution you'd like**

Some possibilities:

* A new item under the "Actions" menu in a media profile that duplicates it to a new profile
* A new item under the "Actions" menu in a media profile that saves the profile as a new preset, so that it's available to choose as a preset when creating a new profile in the future
* Since you can already copy the profile as JSON, allow the ability to edit a profile as JSON. Then you could create a new profile and paste in another profile's JSON for the editable elements (I guess everything except `id`, `inserted_at`, and `edited_at`).

**Comment by kieraneglin** [comment]
Hey there! Thanks for the suggestion (:

Fair enough! Makes sense to get this to feature parity with Sources in this regard. I'll be blunt by saying this isn't the highest priority thing I'm working on, but I'll leave this issue open to track these changes in case I ever need to get something out as a quick win.

If someone stumbles upon this before I get to it and is learning Elixir, this would be a great first PR! There is a perfect prior example with the way you can use a source as a "preset" for another source.

**Comment by loop-index** [comment]
I'd love to try tackling this.
