### ISSUE TITLE
[Triage] Error downloading pending videos

### ISSUE THREAD

**Issue by svthuh** [kieraneglin/pinchflat#462]
**Status**:
`500`

**Reason**:
`%Exqlite.Error{message: "database disk image is malformed", statement: "SELECT o0.\"id\", o0.\"state\", o0.\"queue\", o0.\"worker\", o0.\"args\", o0.\"meta\", o0.\"tags\", o0.\"errors\", o0.\"attempt\", o0.\"attempted_by\", o0.\"max_attempts\", o0.\"priority\", o0.\"attempted_at\", o0.\"cancelled_at\", o0.\"completed_at\", o0.\"discarded_at\", o0.\"inserted_at\", o0.\"scheduled_at\" FROM \"oban_jobs\" AS o0 WHERE (o0.\"state\" IN (?,?,?,?)) AND (datetime(o0.\"inserted_at\") >= datetime(?)) AND ((o0.\"worker\" = ?) AND ((o0.\"queue\" = ?) AND (((SELECT 0 NOT IN (SELECT json_extract(o0.\"args\", '$.' || t.key) = t.value FROM json_each(?) t)\n) AND (SELECT 0 NOT IN (SELECT json_extract(?, '$.' || t.key) = t.value FROM json_each(o0.\"args\") t)\n)) AND ?))) LIMIT 1"}`

**Stacktrace**:
```
    (ecto_sql 3.12.0) lib/ecto/adapters/sql.ex:1078: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto_sql 3.12.0) lib/ecto/adapters/sql.ex:976: Ecto.Adapters.SQL.execute/6
    (ecto 3.12.3) lib/ecto/repo/queryable.ex:232: Ecto.Repo.Queryable.execute/4
    (ecto 3.12.3) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
    (ecto 3.12.3) lib/ecto/repo/queryable.ex:154: Ecto.Repo.Queryable.one/3
    (oban 2.18.3) lib/oban/engines/lite.ex:329: Oban.Engines.Lite.fetch_unique/2
    (oban 2.18.3) lib/oban/engines/lite.ex:63: Oban.Engines.Lite.insert_job/3
    (oban 2.18.3) lib/oban/engine.ex:192: anonymous fn/4 in Oban.Engine.insert_job/3

```
  

**To Reproduce**

Select source, see pending downloads, press download button, receive error

**Expected behavior**
A clear and concise description of what you expected to happen.  To 
 
**Screenshots**

**Diagnostic info**

- App Version: 2024.10.30
- yt-dlp Version: 2024.10.22
- Apprise Version: v1.9.0
- System Architecture: x86_64-pc-linux-gnu
- Timezone: America/Boise

**Additional context**

[pinchflat-logs-2024-11-08.txt](https://github.com/user-attachments/files/17672959/pinchflat-logs-2024-11-08.txt)

**Comment by kieraneglin** [comment]
Hey there! Thanks for the report (:

This isn't an issue with Pinchflat per se, but instead is an SQLite error directly. I put some instructions [here](https://github.com/kieraneglin/pinchflat/issues/450#issuecomment-2455914714) on how to best troubleshoot this

**Comment by svthuh** [comment]
Thank you.  I couldn’t quite figure out how to implement your instructions though in Unraid.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by kieraneglin** [comment]
Fair enough! The instructions are applicable to Unraid as well, but I'll give some tips that might help.

1. These commands are largely run through the _Unraid_ terminal. There's an icon to open the terminal in the upper right of every page
2. Unraid _should_ have sqlite3 installed by default, but you can confirm by running `which sqlite`. If it returns _anything_ that's not a blank line or an obvious error, you're good to go. On my system it returns `/usr/bin/sqlite3`
3. On my setup, the Pinchflat database is stored in `/mnt/user/appdata/pinchflat/db`. This might be different for you, but it's probably the same. This is the directory that you want to back up before making any changes and also it's the directory in which you'll be running the commands outlined
4. You can make a backup after you've stopped the Pinchflat container with `cp /mnt/user/appdata/pinchflat/db /mnt/user/appdata/pinchflat/db_backup`. Then you can run `cd /mnt/user/appdata/pinchflat/db` and run the other commands I've outlined in my other comment

Let me know if that works out for you!
