### ISSUE TITLE
[FR] Global RSS feed

### ISSUE THREAD

**Issue by lamarios** [kieraneglin/pinchflat#463]
**Is your feature request related to a problem? Please describe.**
Adding all sources to a podcast client can be tedious and difficult to maintain as it requires to add the feed url for each source to the client

**Describe the solution you'd like**
A single URL for all the sources

Great application ! Thanks

**Comment by kieraneglin** [comment]
Hey there! Thanks for the report (:

There is a fairly common mechanism for this kind of thing called an OPML file. They're used for mass-exporting RSS feeds for use in a podcast client. There's already #449 so I'll be closing this issue in favour of that, but keep an eye on that one for any updates!

**Comment by lamarios** [comment]
Alright. Thanks. I'll follow this. 

Though a downside of this is that I guess that if I add a new channels to the sources. I'll need to export and import again?
