### ISSUE TITLE
[FR] Plex TV library - Show as Season and Episodes 

### ISSUE THREAD

**Issue by Guruleenyc** [kieraneglin/pinchflat#464]
**Is your feature request related to a problem? Please describe.**
Downloaded channels and videos not showing as TV show and episodes in Plex TV library type. 

**Describe the solution you'd like**
Have YouTube channels appear as TV shows and YouTube channel videos appear as episodes in Plex TV library.

**Comment by kieraneglin** [comment]
Hey there! Thanks for the report (:

Did you follow the [instructions](https://github.com/kieraneglin/pinchflat/wiki/Frequently-Asked-Questions#how-do-i-get-media-into-plexjellyfinkodi) in the documentation? This has worked pretty reliably for most people. Let me know if that changes anything!

**Comment by Yankees4life** [comment]
> Hey there! Thanks for the report (:
> 
> Have you been able to check the [instructions](https://github.com/kieraneglin/pinchflat/wiki/Frequently-Asked-Questions#how-do-i-get-media-into-plexjellyfinkodi) in the documentation? This has worked pretty reliably for most people. Let me know if that changes anything!

You could either follow that or modify the profile settings to name the stuff for it to work with this 
https://github.com/JordyAlkema/Youtube-DL-Agent.bundle

**Comment by kieraneglin** [comment]
Another good option! I've never tried that myself, but I've heard others have good luck with it.

I'll close this out for now, but if you have any trouble feel free to re-open 🤙
