### ISSUE TITLE
[Triage] Channel artwork is not downloaded

### ISSUE THREAD

**Issue by thimplicity** [kieraneglin/pinchflat#467]
**Describe the bug**
Hi, I just started using Pinchflat and I really like its simplicity. I have one problem: When I add a channel as a new source, everything is downloaded fine. The single video artwork/thumbnail is downloaded and visible in Jellyfin, but the channel "icon" and the channel "background" is not. I have ticked all boxes to download additional data etc. in the profile, but no luck. Is that not yet included or am I doing something wrong? "Download Series Images" is activated in the settings.

**Expected behavior**
I would have expected that each channel has an icon (to be shown in the Jellyfin overview) and a "background" (to be shown when opening channel details)

**Screenshots**
![image](https://github.com/user-attachments/assets/610338c2-4b67-47d0-ac0d-c7ab8b8e2fbb)
![image](https://github.com/user-attachments/assets/029be1de-0afe-4bff-a769-bc567a7cb99c)

**Diagnostic info**

- App Version: 2024.10.30
- yt-dlp Version: 2024.10.22
- Apprise Version: v1.9.0
- System Architecture: x86_64-pc-linux-gnu
- Timezone: America/New_York

Thanks!

**Comment by kieraneglin** [comment]
Hey there! Thanks for the report (:

This is a known yt-dlp issue and is covered in #416. Unfortunately, since it doesn't happen to me, I can't produce the necessary logs to help the yt-dlp team troubleshoot.

If you're keen, I've put instructions in #416 on how to grab the info they may need. If you're willing to give those a shot, I'd really appreciate it!

**Comment by thimplicity** [comment]
Hi @kieraneglin,
thanks for following up. Here is the output of the command you mentioned in the linked instructions:

`{"original_url": "https://www.youtube.com/@mkbhd", "thumbnails": [{"url": "https://yt3.googleusercontent.com/KhLiJiH9xE8AiPUz9fLD9rOQYNH_EVhVuaKyAu2hp8alAhtkV4IQ9-Dfsoge8E11Im0nxDgjsQ=w1060-fcrop64=1,00005a57ffffa5a8-k-c0xffffffff-no-nd-rj", "height": 175, "width": 1060, "preference": -10, "id": "0", "resolution": "1060x175", "filepath": "/tmp/image.0.jpg"}, {"url": "https://yt3.googleusercontent.com/KhLiJiH9xE8AiPUz9fLD9rOQYNH_EVhVuaKyAu2hp8alAhtkV4IQ9-Dfsoge8E11Im0nxDgjsQ=w1138-fcrop64=1,00005a57ffffa5a8-k-c0xffffffff-no-nd-rj", "height": 188, "width": 1138, "preference": -10, "id": "1", "resolution": "1138x188", "filepath": "/tmp/image.1.jpg"}, {"url": "https://yt3.googleusercontent.com/KhLiJiH9xE8AiPUz9fLD9rOQYNH_EVhVuaKyAu2hp8alAhtkV4IQ9-Dfsoge8E11Im0nxDgjsQ=w1707-fcrop64=1,00005a57ffffa5a8-k-c0xffffffff-no-nd-rj", "height": 283, "width": 1707, "preference": -10, "id": "2", "resolution": "1707x283", "filepath": "/tmp/image.2.jpg"}, {"url": "https://yt3.googleusercontent.com/KhLiJiH9xE8AiPUz9fLD9rOQYNH_EVhVuaKyAu2hp8alAhtkV4IQ9-Dfsoge8E11Im0nxDgjsQ=w2120-fcrop64=1,00005a57ffffa5a8-k-c0xffffffff-no-nd-rj", "height": 351, "width": 2120, "preference": -10, "id": "3", "resolution": "2120x351", "filepath": "/tmp/image.3.jpg"}, {"url": "https://yt3.googleusercontent.com/KhLiJiH9xE8AiPUz9fLD9rOQYNH_EVhVuaKyAu2hp8alAhtkV4IQ9-Dfsoge8E11Im0nxDgjsQ=w2276-fcrop64=1,00005a57ffffa5a8-k-c0xffffffff-no-nd-rj", "height": 377, "width": 2276, "preference": -10, "id": "4", "resolution": "2276x377", "filepath": "/tmp/image.4.jpg"}, {"url": "https://yt3.googleusercontent.com/KhLiJiH9xE8AiPUz9fLD9rOQYNH_EVhVuaKyAu2hp8alAhtkV4IQ9-Dfsoge8E11Im0nxDgjsQ=w2560-fcrop64=1,00005a57ffffa5a8-k-c0xffffffff-no-nd-rj", "height": 424, "width": 2560, "preference": -10, "id": "5", "resolution": "2560x424", "filepath": "/tmp/image.5.jpg"}, {"url": "https://yt3.googleusercontent.com/KhLiJiH9xE8AiPUz9fLD9rOQYNH_EVhVuaKyAu2hp8alAhtkV4IQ9-Dfsoge8E11Im0nxDgjsQ=s0", "id": "banner_uncropped", "preference": -5, "filepath": "/tmp/image.banner_uncropped.jpg"}, {"url": "https://yt3.googleusercontent.com/lkH37D712tiyphnu0Id0D5MwwQ7IRuwgQLVD05iMXlDWO-kDHut3uI4MgIEAQ9StK0qOST7fiA=s900-c-k-c0x00ffffff-no-rj", "height": 900, "width": 900, "id": "7", "resolution": "900x900", "filepath": "/tmp/image.7.jpg"}, {"url": "https://yt3.googleusercontent.com/lkH37D712tiyphnu0Id0D5MwwQ7IRuwgQLVD05iMXlDWO-kDHut3uI4MgIEAQ9StK0qOST7fiA=s0", "id": "avatar_uncropped", "preference": 1, "filepath": "/tmp/image.avatar_uncropped.jpg"}]}`
