### ISSUE TITLE
[FR] Downloading channel descriptions and other channel metadata

### ISSUE THREAD

**Issue by ggttttggggtt** [kieraneglin/pinchflat#472]
**Is your feature request related to a problem? Please describe.**
Currently Pinchflat doesn't have the capability to download channel descriptions or other metadata like playlists or community pages.

**Describe the solution you'd like**
A category in the source config for channel metadata.

**Describe alternatives you've considered**
Toggles under the regular metadata category instead.

**Additional context**
I'm not sure if yt-dlp can download playlist or community page metadata but it can download channel descriptions.

**Comment by kieraneglin** [comment]
Hey there! Thanks for the suggestion (:

I must have missed this! Currently, Pinchflat can indeed download the description of a channel or playlist if it exists (see screenshot).

I don't think there's support for playlists or community pages in any meaningful sense, but could you give me an example for both of these of a channel that has them and what you'd expect to be stored in Pinchflat?

![Screenshot 2024-11-15 at 12 46 22 PM](https://github.com/user-attachments/assets/cad67efd-2a46-4e18-aba4-2bd2196ed694)
