### ISSUE TITLE
[FR] Other Webhooks (or Plex (Autoscan) integration)

### ISSUE THREAD

**Issue by Yankees4life** [kieraneglin/pinchflat#473]
While we wait for the slow acting ytdlp devs to update your PR, 
https://github.com/kieraneglin/pinchflat/issues/139

I think it would be a good idea, to set up another webhook so that we can use something like autoscan to update the plex/emby/jellyfin library after the download of a video (or entire channel) is completed instead of relying on real time monitoring as sometimes that'll pick up files that are still processing

**Comment by kieraneglin** [comment]
Hey there! Thanks for the suggestion (:

This already exists! Someone has an example script [here](https://github.com/kieraneglin/pinchflat/issues/214#issuecomment-2094946216).

If that doesn't work for you, feel free to re-open this issue 🤙

**Comment by Yankees4life** [comment]
> Hey there! Thanks for the suggestion (:
> 
> This already exists! Someone has an example script [here](https://github.com/kieraneglin/pinchflat/issues/214#issuecomment-2094946216).
> 
> If that doesn't work for you, feel free to re-open this issue 🤙

Ok...seems like that working. I had set up a rewrite in the autoscan settings in order to for it to find the file inside my container but it seems like its working
