### ISSUE TITLE
Ntfy Support

### ISSUE THREAD

**Issue by Rom0067** [kieraneglin/pinchflat#475]
**Describe the solution you'd like**

I use ntfy for all of my selfhosted apps and I think it would be awesome if pinchflat had ntfy integration.  Thank you!

https://github.com/binwiederhier/ntfy

**Comment by kieraneglin** [comment]
Hey there! Thanks for the suggestion (:

Pinchflat already has Apprise support (Config > Settings) and from what I can see it looks like there's a NTFY provider for Apprise ([link](https://github.com/caronc/apprise/wiki/Notify_ntfy)).

Does this do what you need?

**Comment by Rom0067** [comment]
> Hey there! Thanks for the suggestion (:
> 
> Pinchflat already has Apprise support (Config > Settings) and from what I can see it looks like there's a NTFY provider for Apprise ([link](https://github.com/caronc/apprise/wiki/Notify_ntfy)).
> 
> Does this do what you need?

Well that is embarrassing!  I had no idea apprise would work with ntfy.  I'm sorry to have wasted your time.  Thank you I believe this will work just fine.

**Comment by kieraneglin** [comment]
No problem! If you run into any trouble feel free to re-open this issue or make a new one (:

**Comment by Rom0067** [comment]
> No problem! If you run into any trouble feel free to re-open this issue or make a new one (:

Worked perfectly thanks again!
