### ISSUE TITLE
[FR] Customize notification target per source

### ISSUE THREAD

**Issue by dlfigueira** [kieraneglin/pinchflat#477]
Even though it is possible to send notifications via Apprise for downloaded media, it is not possible to customize the target on a per source basis. 

In some situations, one person could be interested in a set of sources whilst another would be interested in another set of sources. Thus, it would be helpful to be able to override the notification settings per source.

**Comment by kieraneglin** [comment]
Hey there! Thanks for the suggestion (:

I like the thought here, but I don't think this is something that fits well in-app at this point. While it's not a perfect replacement, you can get something pretty similar with [custom lifecycle scripts](https://github.com/kieraneglin/pinchflat/wiki/%5BAdvanced%5D-Custom-lifecycle-scripts) or possibly even using [ntfy](https://docs.ntfy.sh) as a middleman
