### ISSUE TITLE
[Triage] video downloaded with wrong audio track (automatic dubbing)

### ISSUE THREAD

**Issue by gfabrizi** [kieraneglin/pinchflat#482]
**Describe the bug**

I've been using Pinchflat for months with great results (thanks so much for the great app <3)
I don't know if it's a bug or a missing feature, but in the last few days I've been noticing a problem with downloading some videos.
I follow some Italian creators and for some reason Pinchflat downloads the videos with audio automatically translated into English (generated with the automatic dubbing feature of youtube).
There are no other audio tracks embedded in the video file.
I haven't found a way from Pinchflat to set a preferred language for the audio (like there is for subtitles) or tell it to ignore the audio track automatically generated by Youtube.

**To Reproduce**

1. add this channel as source: https://www.youtube.com/@Prattquello
2. sync latest videos
3. the last (at the moment) video has english audio

Direct link to a problematic video: https://www.youtube.com/watch?v=4yj3MilklIM

**Expected behavior**

Download video with audio track in the main language

**Diagnostic info**

- App Version: 2024.10.30
- yt-dlp Version: 2024.10.22
- Apprise Version: v1.9.0
- System Architecture: x86_64-pc-linux-gnu
- Timezone: Europe/Rome

**Additional context**

I’m using Pinchflat docker image with docker compose

**Comment by sebastianschauenburg** [comment]
This indeed started a short time ago. I noticed this also at the "Autodoktoren" channel. Don't know if it is a setting of the content creators, or a 'feature' which has been automatically added.

It would be great if a kind of language code filter would be allowed ;-)

P.S. I also completely agree with the sentiment that the app is excellent. Many thanks!

**Comment by kieraneglin** [comment]
Hey there! Thanks for the report (:

This is strange! Truthfully, I didn't know this feature even existed. Looking into it, it seems like this _may_ have been a mistake by the uploader. You can see here that while Italian is marked as the original language, English is marked as the default:

![Screenshot 2024-11-25 at 2 53 27 PM](https://github.com/user-attachments/assets/c2e40dfe-e649-4a48-9f11-1923f64ad02a)

However, I'm not sure if that's actually the uploader's fault or if `yt-dlp`'s video extractor inadvertently prefers English.

In any case, I agree that it's a good idea to allow for configuration of this option! I'll look into that once I have time. Until then, you can use [Custom yt-dlp Options](https://github.com/kieraneglin/pinchflat/wiki/%5BAdvanced%5D-Custom-yt%E2%80%90dlp-options) to force the preference of your language. Just add `--extractor-args "youtube:lang=it"` to `base-config.txt` (or whatever file you think is appropriate) and it'll download in Italian! You can swap the `it` for `de` or any other language code.

---

(Note to self) When looking into this, see if there's a way to sort the `MORE INFO` column of the formats table to prefer audio that has the string `original` in it
