### ISSUE TITLE
[Triage] Unicode characters not preserved

### ISSUE THREAD

**Issue by nebula-it** [kieraneglin/pinchflat#483]
**Describe the bug**

When downloading a video with `?` (Unicode: `003F`) in title it gets converted to `？` (Unicode: `FF1F`). [This link](https://apps.timwhitlock.info/unicode/inspect?s=%3F%EF%BC%9F) shows the difference, the first is from the youtube and second is from the file saved on disk.

**To Reproduce**

1. Add this playlist as source and set it to not download (we dont want to download all of it for testing): https://www.youtube.com/playlist?list=PLoILbKo9rG3skRCj37Kn5Zj803hhiuRK6
2. Go to sources and then the source we just added above, if custom name was not used it should be `Go Class`
3. In the pending tab, search for `Intro and Why`, that should bring the first video from playlist, click and open it
4. Then from the `Actions` button select `Force Download`
5. Check the file name of downloaded file, the `?` at the end is different unicode character than UI or youtube itself.

**Expected behavior**
The `?` should be unicode char `003F`

**Additional context**
The output_path_template is `/playlists//{{ source_custom_name }}/%(playlist_index)s-{{ title }}.{{ ext }} `

**Comment by nebula-it** [comment]
It might be something else, I tried with metube and it results in the same result. So maybe its the ytdl doing something or the original author used `FF1F` in the title and its youtube UI normalizing it.
Either way, dont spend too much time looking into it :) You have other things to focus on, this is a minor inconvenience.

**Comment by kieraneglin** [comment]
Hey there! Thanks for the report (:

This is expected behaviour - yt-dlp replaces certain characters with their full-width unicode counterparts to ensure filenames with restricted characters work on all major OS' ([see here](https://github.com/yt-dlp/yt-dlp/blob/4b5eec0aaa7c02627f27a386591b735b90e681a8/yt_dlp/utils/_utils.py#L639))
