### ISSUE TITLE
[Triage] Latest update breaks pod hardening - [error] | Permissions check failed: {:error, :erofs}

### ISSUE THREAD

**Issue by davralin** [kieraneglin/pinchflat#489]
**Describe the bug**
Latest release doesn't start due to `[error] | Permissions check failed: {:error, :erofs}`.
Downgrading works again.

**To Reproduce**
I run pinchflat in kubernetes, with tweaks to the hardening - this worked fine in the previous version, but it broke in the latest version.

The hardening sets:
````
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
        supplementalGroups: [10000]
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities: { drop: ["ALL"] }
````

This is the logs:

````
$ kubectl -n media logs -f deploy/pinchflat
2024-11-29 15:41:55.399 [info] | Checking permissions for /config
2024-11-29 15:41:55.402 [info] | Permissions OK
2024-11-29 15:41:55.402 [info] | Checking permissions for /downloads
2024-11-29 15:41:55.402 [info] | Permissions OK
2024-11-29 15:41:55.402 [info] | Checking permissions for /etc/yt-dlp
2024-11-29 15:41:55.408 [error] | Permissions check failed: {:error, :erofs}
** (RuntimeError) Unknown error
    (pinchflat 2024.11.27) lib/pinchflat/release.ex:57: anonymous fn/1 in Pinchflat.Release.check_file_permissions/0
    (elixir 1.17.0) lib/enum.ex:987: Enum."-each/2-lists^foreach/1-0-"/2
    nofile:1: (file)
    (stdlib 5.2.3) erl_eval.erl:750: :erl_eval.do_apply/7
    (elixir 1.17.0) lib/code.ex:572: Code.validated_eval_string/3
Filesystem error. Exiting.
````

**Expected behavior**
Normal start.

**Screenshots**

N/A

**Diagnostic info**

N/A

**Additional context**

https://github.com/davralin/cluster-ops/blob/main/kubernetes/apps/media/pinchflat/helm-release.yaml

**Comment by kieraneglin** [comment]
Hey there! Thanks for the report (:

This is because I've added support for yt-dlp plugins and they require a specific directory to be writable. See #488 for more!

**Comment by davralin** [comment]
Thanks! Works great now, I took the liberty of referencing how I fixed it in my repo here, in case someone else catches it.

Think I must have missed the bug from onedr0p, simply because it was closed.
