### ISSUE TITLE
[FR] Map download path to a Media Profile

### ISSUE THREAD

**Issue by Charles-Em** [kieraneglin/pinchflat#496]
Hello,

Do you think it would be feasible to have the possible to override the download path mapping at Media Profile level.
This way I could directly chose to which part of the network I want a playlist to be stored.
Dunno if it this makes sense to you.

Regards,
Charles

**Comment by kieraneglin** [comment]
Hey there! Thanks for the request (:

This makes sense, but it'd be difficult to implement while keeping things simple for the average user so I doubt I'll add this as a feature. 

What I've been doing instead and what I've recommended to others is to use a symlink. Create a symlinked directory in your Pinchflat download directory called, say, `Drive_2` and in your output template do something like `/Drive_2/{{ title }}. {{ ext }}`
