### ISSUE TITLE
[FR] User sortable columns in sources list

### ISSUE THREAD

**Issue by robertkleinschuster** [kieraneglin/pinchflat#502]
To find sources with the most pending downloads it would be nice to be able to sort by the pending column by clicking on the heading.

This is useful if some channels upload lots of videos and it can keep up with downloading and you want to find the sources responsible.
Or if you run out of storage you might want to find sources with lots of downloads.

<img width="1448" alt="Bildschirmfoto 2024-12-11 um 18 28 04" src="https://github.com/user-attachments/assets/0bf02d4d-f256-4f13-bac2-577c7b673bf7" />

**Comment by kieraneglin** [comment]
Hey there! Thanks for the suggestion (:

Fair enough! I have a whole laundry list of changes I'd like to make to the sources and media profiles table. That's something I'd like to tackle soon, time permitting 🤙
