### ISSUE TITLE
[FR] Implement a "Feed" of downloaded videos

### ISSUE THREAD

**Issue by robertkleinschuster** [kieraneglin/pinchflat#504]
It would be nice to have a dedicated view that displays basically the same as the Media History but filtering out not downloaded videos.

This could then be used as a feed to watch videos directly in Pinchflat. I think the video detail view is already quite nice and it is a shame that it is a bit hidden away.

<img width="1412" alt="Bildschirmfoto 2024-12-11 um 18 31 31" src="https://github.com/user-attachments/assets/f5f42799-9241-4931-b779-4a9f3d66a983" />

<img width="1433" alt="Bildschirmfoto 2024-12-11 um 21 32 53" src="https://github.com/user-attachments/assets/56855742-d73c-42c7-99a6-1f416460344d" />

**Comment by kieraneglin** [comment]
I dig it! This would fit in well with #478

I see you're working on something in your fork - I'd maybe recommend to hold off for a bit because I'd like to look into a bit of a refactor for how I'm handling tables in general. I'll let you know when/if I end up making those changes!

**Comment by robertkleinschuster** [comment]
I first didn’t quite understand what was meant with #478 but now i see what you are going for.

I saw that there’s a bit of duplicate code but I think it’s OKish at the moment for what it is.

When touching this more broadly I would also recommend moving away from “real” html tables as they are kind of a pain on mobile. Rather design some responsive layout that folds out and expands on desktop.

In the long run it might be an idea having a general media item view which can be initialized with different filters and sorting options.

But I think that’s a bit out of scope here. If I’m motivated enough, i might look into it.

**Comment by kieraneglin** [comment]
> In the long run it might be an idea having a general media item view which can be initialized with different filters and sorting options.

This is, ideally, the end goal of my refactor. A generalized system for tables where you just have to provide methods for how to fetch/sort/filter data and it does the rest. I'm not sure whether I'll be able to fully realize that, but I'm sure I can make a better system than what currently exists
