### ISSUE TITLE
Truncate media items, sources, jobs via css

### ISSUE THREAD

**Issue by robertkleinschuster** [kieraneglin/pinchflat#506]
It is preferred to truncate text via css and not via server side functions because the browser will show more on larger screens and on smaller screens will show a tooltip with the complete text on mouseover.

<img width="425" alt="Bildschirmfoto 2024-12-11 um 21 46 39" src="https://github.com/user-attachments/assets/d64b4929-779d-4d8c-8f4c-9c103419ee78" />

Using tailwind use class="truncate max-w-xs" on columns to be truncated.

**Comment by kieraneglin** [comment]
Oh hell yeah. Bluntly, I didn't know you could do that! I'm a backend guy through and through so there are large gaps in my knowledge of CSS capabilities

**Comment by robertkleinschuster** [comment]
In the PR I intentionally didn’t do the headings yet. Will do a separate one for that.

is this something that should/can be covered by the test infrastructure in place at the moment?

Just asking because I never worked with elixir and the frameworks around it. Are there UI tests?

**Comment by kieraneglin** [comment]
There aren't UI tests per se, but there are tests that check the rendered HTML response from the controller. I don't think that'll help in this case so I'm perfectly okay with the current tests that just check for the presence of the `custom_name` in the response
