### ISSUE TITLE
Data Import

### ISSUE THREAD

**Issue by Ich0818** [kieraneglin/pinchflat#519]
Hi guys,

I am currently using the Jeeaaasus/youtube-dl container, but it seems the developer has abandoned the project, so I am looking for a new downloader. The current container saves already downloaded videos in an archive.txt file like this:
youtube uhKAbsMJAgU  
youtube bLiEss_l-ZM  
youtube jwAg5mkgefw  

Is it possible to import the data from this file into the PinchFlat database? I absolutely don’t want to download all the videos again.

Thanks!

**Comment by kieraneglin** [comment]
Hey there! Thanks for the question (:

Unfortunately there is no way to import data from other apps into Pinchflat, nor is it a planned feature. Pinchflat's internal data model is much more structured than a lot of similar apps which has some benefits, but the downside is that import of unstructured data is not a trivial task. I wish I had better news, but at the moment it's not something I'm expecting to add
