### ISSUE TITLE
[FR] One-season media center profile

### ISSUE THREAD

**Issue by ggttttggggtt** [kieraneglin/pinchflat#523]
**Is your feature request related to a problem? Please describe.**
Ideally I want exactly the setup of the media center profile, but without videos being split into a different season for each year. This makes it difficult to browse some long running channels especially if they were more active some years than others.

**Describe the solution you'd like**
A preset for this.

**Describe alternatives you've considered**
None.

**Additional context**
Maybe there is a way to do it already, but I couldn't figure out how.

**Comment by kieraneglin** [comment]
Hey there! Thanks for the suggestion (:

I won't be adding this as a preset, but you can do this by using the existing Media Center profile and swapping out `{{ season_by_year__episode_by_date_and_index }}` for `{{ static_season__episode_by_date }}`. There's a blurb with a few other options at the bottom of the Media Profile form!
