### ISSUE TITLE
[FR] YouTube Music Playlist created Plex playlist

### ISSUE THREAD

**Issue by memphisraynz** [kieraneglin/pinchflat#525]
**Is your feature request related to a problem? Please describe.**
Not related to any issues.

**Describe the solution you'd like**
YouTube Music provides some nice music playlists. It would be great to download the audio and then pass through to Plex the playlist/m3u to have the same playlist available in Plex.

**Describe alternatives you've considered**
I have come across, but not yet tried, the ability to perform a POST request to the Plex server to create the playlist.

**Additional context**
None.

**Comment by memphisraynz** [comment]
Thought I would add some resources to help with this.
I was able to create a playlist via API and then add items to it, overall it is a pretty simple process. 

There is an API wrapper - https://python-plexapi.readthedocs.io/en/latest/modules/playlist.html#
As well as this Github collection of scripts - https://github.com/Casvt/Plex-scripts/tree/main/playlist_collection

The end user could be responsible for marrying up the Pincflat download folder and the Plex Music folder, EG:
Plex (from API XML): file="/media/video/music/Addison Rae/Addison Rae - Diet Pepsi (Official Video).m4a"
Pinchflat: media_filepath: /downloads/music/Addison Rae/Addison Rae - Diet Pepsi (Official Video).m4a

That could be used to obtain the Plex library file id, then adding to the playlist

**Comment by kieraneglin** [comment]
Hey there! Thank you for the suggestion (:

I like this idea, but I don't think it's a good fit with the project. I definitely see the utility, but adding something like this opens a can of worms in the sense that I'm now tightly coupling some in-app functionality with one specific external application. 

Although I don't see this being added as a first-party feature, you may be able to do this with [Pinchflat's Custom Lifecycle Scripts](https://github.com/kieraneglin/pinchflat/wiki/%5BAdvanced%5D-Custom-lifecycle-scripts)! If you try this approach and get it working, I'd love to see how you handled it! I've been meaning to make a repository of useful user scripts but I haven't gotten around to it yet.

**Comment by memphisraynz** [comment]
Hopefully this doesn't re-open this.
Thanks for reviewing and considering.

I use HomeAssistant and already had Node-Red running, so I am utilising it to build the playlists
1. Sending Post with the filepath, custom_name and title [lifecycle](https://gist.github.com/memphisraynz/1659d49398c733264445629f03fdf322)
2. Node-Red then parses this and adds it to a json file based on the custom_name, Initially the Library id is null
`[
    {
        "id": "31407",
        "artist": "Post Malone, Doja Cat",
        "title": "I Like You (A Happier Song)",
        "media_filepath": "/media/music/Post Malone, Doja Cat/I Like You (A Happier Song).m4a",
        "plexLibraryId": "13696"
    }
]`
3. On a interval timer, Node-Red is getting all those json files and querying pllex to find the plex file and updates the json with the plexLibraryId
4. On a interval timer, Node-Red is then reviewin all those files and sending the songIds to the relevant playlist

I'm having different issues with downloading, but from quick testing it works.
