### ISSUE TITLE
Option to download only new - not whole channel/playlist?

### ISSUE THREAD

**Issue by TekWarren** [kieraneglin/pinchflat#60]
This looks super clean and was easy to get setup. The only thing I was wishing for was an option to choose only NEW videos from a channel vs all. 

If I had to add anything else it would be the option to specify a time for the index also. For example, checking/downloading at a specific time.

Very awesome project, high hopes for you!

**Comment by kieraneglin** [comment]
Thank you very much! That's a fair shake, I'll add it to the list. 

I'm currently working on a mechanism to greatly speed up indexing in certain cases. I'll let you know once that's pushed because it might be an alternative solution for the indexing time feature. 

Thank you for the feedback! 🙌🏻

**Comment by kieraneglin** [comment]
To elaborate, indexing at a specific time is difficult in the cases where the time it takes to index is greater than the period between index runs. More clearly, if you have it set to run at midnight each night but indexing takes 26 hours, that's a problem. Some similar apps run to this issue so I intentionally took a slightly different approach with index scheduling to avoid this. 

There are definitely ways around it if that's what it comes to, but I'm hoping the fast indexing approach will make this problem mostly irrelevant 🤞🏻

**Comment by TekWarren** [comment]
Appreciate the reply and open-ness to suggestions. Makes sense about the indexing. Look forward to the possibility of the "only new" videos from a channel versus ALL. 

Also had a thought for my timing based scenario. Perhaps the docker container itself could be scheduled to be "up" only certain hours of the day.

**Comment by kieraneglin** [comment]
@TekWarren Done! I've Added the ability to specify a cutoff date for a Source where only videos created on or after that date will be downloaded. To get the behaviour you want you can set it to the current day but you can also set it to any other day past or future (not sure why you'd want future but I'm not here to judge). This shouldn't act weird for existing media/Sources, but it won't delete any old media or anything. You'll need to add a new Source to get the full effect.

I've also implemented fast indexing for Media Profiles. This performs an initial "slow" index, then schedules followup slow indexes monthly. In the meantime, it runs a very fast and lightweight index every 15 minutes using an RSS feed and updates/downloads based on that. There's a whole spiel on the Media Profile form that explains it well.

I've pushed the release and it should be available on Unraid within ~2 hours, but you can force update the container if you want it sooner. With that I'm going to close this issue, but please open a new one if you see fit!

Thanks again for the feedback 🤙
