### ISSUE TITLE
Proposed Logo Designs

### ISSUE THREAD

**Issue by hernandito** [kieraneglin/pinchflat#64]
Hi,

I took the liberty in creating a few logo/icon variations. The one you currently use feels too generic/plain.

I don't know the genesis of the name "Pinchflat"; but I tried to do something with it. Same with the current teal color.

I created two main variations. One using the teal color, and one with a more direct relation with the YouTube logo. I am tending towards the teal option. The red feels too close to YouTube.

I will explain each variation:
The "v.A" down arrow versoiin = a play on the YouTube play button but rotated to imply more of a download concept. The cookie bite is to make it less generic.

The "v.B" is plainly the letter P sideways. Rotated to make is not look like a letter, and also is is facing "down" as in download.

The "v.C" is for indicating you are collecting individual's YouTube channels. From what I see in your program, you are downloading the content of a per channel basis.
The "v.D" option is similar to "A" without the cookie bite, and it is still implying both download and the play button idea. This is my least favorite as I think it comes to close to looking like a lock.

Versions E to G are all variations of the same idea. The use of a paper clip to organize things together. A paper clip "pinches" papers together. And the down arrow implies download.

I am pasting the images below. I have done them at around 1200px each. But I think they need to be seen in lower resolution for proper evaluation.

![image](https://github.com/kieraneglin/pinchflat/assets/787317/80b06a38-bd8e-42fe-b21c-a3181dc696f0)

Please let me know if you like them. Please do not feel obliged to implement. As someone in the creative field, I understand getting ideas rejected. 

I do have a favorite... but I will not influence. 

Please let me know, and we can expand adding the word "Pindash" for a full logo.

Thanks.

**Comment by kieraneglin** [comment]
First of all, thank you so much for this! It's extremely thoughtful for you to put these together. This is why I love the OSS community!

I'll be the first to say that I didn't put a lot of thought into the current logo and I'm open to improvements! These suggestions aren't jumping out to me but I'll lay out the meaning behind the name and maybe that'll offer some insight :)

The name isn't... clever. I'm a backend developer and my weaknesses are design and marketing! My thought process was that all similar apps have "Tube" in their name and I didn't want to copy that (or else I would've just called it Tubarr LMAO). I'm an avid mountain biker so my mind went in that direction - a pinch-flat is something that can happen when you have a _tube_ in your tires. Like I said, it's not very clever but that was my thought process at the time and it stuck because it was different.

---

The current logo has a few of those elements - it's round to represent a tire and it's _slightly_ flat on the bottom to represent the actual pinch-flat. It's not much and, again, I'm not very attached to the current logo, but it's what I could come up with at the time!

Thank you for the feedback and let me know if you have any other questions :)

**Comment by hernandito** [comment]
Hi,

Thanks for the explanation.... Based on that, I tried the below ideas. From right to left, they start more realistic and them progress to more abstract.

![image](https://github.com/kieraneglin/pinchflat/assets/787317/b8dd1efa-a583-4469-be08-d17539dd1ab6)

Thanks.

**Comment by hernandito** [comment]
Kinda liking these.... same exact transparent .png logo overlaid on both a white and a black background.

![image](https://github.com/kieraneglin/pinchflat/assets/787317/180db8f7-ab85-44a8-9034-fb8bdf0b8935)

**Comment by kieraneglin** [comment]
I'm liking this quite a bit! Beggars can't be choosers and all, but could it be possible to try using something like 5 or 6 spokes? That way each "wedge" between the spokes would also look like a play button.

Not sure if that'll work out in practice, but it's just a thought. Thanks again for this!

**Comment by hernandito** [comment]
Thoughts?
![image](https://github.com/kieraneglin/pinchflat/assets/787317/b92adf67-22d3-4963-ae64-0403c789ec2e)

![image](https://github.com/kieraneglin/pinchflat/assets/787317/907810fc-936a-4442-af89-d84e2fb40b0b)

Does the 6 spoke wheel look too much like a lemon slice? 

I tried 5 spokes, but it looks odd when trying to highlight the "play" button...

![image](https://github.com/kieraneglin/pinchflat/assets/787317/5e853071-6388-440c-86e6-df53e09bcc4b)

**Comment by kieraneglin** [comment]
I'm really liking `1h` and `1i`with a preference for `1i` - what are your thoughts? The only problem is that it kind of looks like a [Sun Cross](https://en.wikipedia.org/wiki/Sun_cross) which is NOT something I want to associate with 🙃 

I'm no good with Photoshop so I made this in a CAD modelling software, but it's an idea to get the 5 spokes looking a little more like a play button. The main difference is not tapering the spokes and I've also added a touch more "material" at the bottom of the wheel so that line doesn't get as thin. What do you think about something in this style?

Again, thank you for your continued help here! It really is appreciated

![Screenshot 2024-03-11 at 3 37 31 PM](https://github.com/kieraneglin/pinchflat/assets/569917/076a9531-5140-4526-8c1e-f689bcf0e936)

**Comment by hernandito** [comment]
Hi... Nice.... Let me work out the 5 spokes to look a bit more like your image. We need to thicken the line strokes so they don't disappear at smaller resolutions.

**Comment by hernandito** [comment]
IMHO... we have a winner... 
![image](https://github.com/kieraneglin/pinchflat/assets/787317/b436fdbe-4772-4170-93b9-0e5b7228f3b2)

Here they are shown smaller, as this is most likely whow you will see them:
![image](https://github.com/kieraneglin/pinchflat/assets/787317/846c4b07-6ecd-4adb-91e5-0ae29dac4a18)

I need to tweak the colors to make them brighter. In Firefox the colors are darker, more muted. I Think it's one of those Adobe sRGB profile things. The FF images below are double muted... but you can see the difference.

![image](https://github.com/kieraneglin/pinchflat/assets/787317/a5ff7754-62b4-44c6-9621-9049c3776bb3)

**Comment by hernandito** [comment]
I think it's Github that mutes the colors. When I lok at my docker's page, the icons looks nice a bright. Below, not so much.

![image](https://github.com/kieraneglin/pinchflat/assets/787317/bbc3b75c-de36-467a-902a-e1bcb31af296)

**Comment by kieraneglin** [comment]
These are great! Love it.

Could I grab 1L and 1N from you so I can test them out in-app? Just to see how they look as a favicon and stuff like that

**Comment by hernandito** [comment]
We can tweak colors easily once you try out.

![Pinchflat v  1L - Full Size](https://github.com/kieraneglin/pinchflat/assets/787317/30944005-5dc9-474a-9b64-ca251b0384c5)
![Pinchflat v  1N - Full Size](https://github.com/kieraneglin/pinchflat/assets/787317/7d4142f6-b723-424d-bc3d-51f45d660f9f)

**Comment by hernandito** [comment]
Try this as the icons...

Maybe we need to make the teal a litlle lighter. The icon will always have the dark blue background used in the UI. Needs a little tweaking.
![Pinchflat v  1N -Icons](https://github.com/kieraneglin/pinchflat/assets/787317/9b40196f-6cba-4b1d-b610-025b108e24e7)

**Comment by hernandito** [comment]
Sorry for all the quick updates.... Here is a better explanation.

Below are some options for what would be the "icons", used in the Docker page of unRAID and the favicon. The earlier larger png.s would be used in your web UI and any type of printed documentation or TV commercials. We would need to adjust the teal color of the earlier pngs to match your color choice of the icons below.

![image](https://github.com/kieraneglin/pinchflat/assets/787317/e290d055-e9a3-4a47-b25b-862d621bccbd)

I am kind of partial to the Pepsi version; I like that palette.

**Comment by hernandito** [comment]
Another overall shape idea...

This one shows the tire, a download button, and a "Y" for YouTube.

![image](https://github.com/kieraneglin/pinchflat/assets/787317/8b55026a-ca9f-46ee-9668-8216e8c39eeb)

**Comment by kieraneglin** [comment]
Great! I'm just finishing up with a big refactor then I'll get right back to this

**Comment by kieraneglin** [comment]
I haven't checked out the Unraid icons yet, but I've added both the earlier candidates to the app to test it out. I _really_ like them, but I'm not sure which I like more! The 5-spoke has a better "play button" imo, but the 3-spoke looks really good in-context as well.

Before looking at it in-app I was 80% 5-spoke and 20% 3-spoke, now I'm more like 60/40. I _think_ I like the 5-spoke more but it's a close race!

![Screenshot 2024-03-12 at 11 03 22 AM](https://github.com/kieraneglin/pinchflat/assets/569917/86e0434f-1e66-46f7-8b26-92656d11f399)
![Screenshot 2024-03-12 at 11 04 07 AM](https://github.com/kieraneglin/pinchflat/assets/569917/03c77a63-d520-40d9-b6cc-9820c8e79450)

**Comment by hernandito** [comment]
A little more to add... I am going to be unavailable for the next 8 hours or so.

![image](https://github.com/kieraneglin/pinchflat/assets/787317/4fb1aa05-cee4-41d1-8f3f-8fcf38b9e012)

**Comment by hernandito** [comment]
Don't be afraid to make the logo and the word bigger. Like double... right now it's smaller than the  "New Sources" element.

**Comment by kieraneglin** [comment]
> Try this as the icons...

I think the middle one is my favourite when testing in my Unraid instance

> Don't be afraid to make the logo and the word bigger. Like double... right now it's smaller than the "New Sources" element.

Good call! I'll try that now

> I am going to be unavailable for the next 8 hours or so

No worries! Thanks again 🤙🏻

**Comment by kieraneglin** [comment]
I had to stop testing to fix a bug so this is kinda half-baked (especially in terms of alignment), but I think I like the white text with the teal logo. I tried full-teal and I think it was too much.

The Github logo will have to be full teal to work on light and dark mode, but in-app I think  I prefer the white

![Screenshot 2024-03-12 at 12 02 48 PM](https://github.com/kieraneglin/pinchflat/assets/569917/3c14f63b-0845-4ffe-8ab8-d035c8070183)

**Comment by hernandito** [comment]
Try this one for the whole logo and wordmark.... not sure how it will look at the proper scale. Then we can summarize which option with which color and tire you prefer for logo, icon, and full logo/wordmark. The color profiles are driving me crazy... Please try it using the transparent .png below.

![image](https://github.com/kieraneglin/pinchflat/assets/787317/a02b7d3f-1e02-4f42-b107-cdffc89a2a21)

![Wordmark v 1a](https://github.com/kieraneglin/pinchflat/assets/787317/efd68369-b4c4-4e0c-a9a4-32a9b45bf258)


And

![image](https://github.com/kieraneglin/pinchflat/assets/787317/9f33fd11-f8e6-4660-a89a-27fd0cf7a94b)

![Wordmark v 1b](https://github.com/kieraneglin/pinchflat/assets/787317/3c55764b-f9e7-4c57-91f9-25c906a39337)


and finally with the wordmark larger:

![image](https://github.com/kieraneglin/pinchflat/assets/787317/5262a16b-f6b1-413a-b2c1-71132c37b1bd)

![Wordmark v 1c](https://github.com/kieraneglin/pinchflat/assets/787317/e26adfaa-017a-474d-ac08-3f1f792147c4)

**Comment by hernandito** [comment]
I like this..... I don't think the teal is needed. It's not tied to anything.

![image](https://github.com/kieraneglin/pinchflat/assets/787317/853e81e9-6849-4ed1-aaaf-6d7c331ec8d2)


![image](https://github.com/kieraneglin/pinchflat/assets/787317/ad886872-a008-45eb-8102-dced4d9d823c)

**Comment by kieraneglin** [comment]
I like that! Would you mind showing the teal logo with white lettering as a comparison? I agree it's not tied to anything directly, but I think it's a nice visual break.

I'll also take a look at this once I can, but I'm working on adding support for NFO metadata. I'll switch back to this as soon as I've made some progress there!

**Comment by hernandito** [comment]
![image](https://github.com/kieraneglin/pinchflat/assets/787317/62e3d045-8c89-464b-91c7-8b00a48aa777)

**Comment by kieraneglin** [comment]
I haven't forgot about this! I was caught up working on #77. I'm going to get one more round of refactors in and hopefully come back to this later today 🤞

**Comment by hernandito** [comment]
Hi... I am a fan of the 3-spoke wheel... The 5-wheel feels slightly old-fashioned. Like a wagon wheel or a water wheel... When you go smaller for the icon and favicon, the additional spokes will get very thin.

The 3 spokes has a sense of forward movement. It also better balances with the word. Pinchflat. Look how strong it compare with all other docker icons:

![image](https://github.com/kieraneglin/pinchflat/assets/787317/cc9cd566-9975-431e-87f5-f79f712dd7e9)


But for me it's a 60-40 split.

**Comment by kieraneglin** [comment]
That picture of your Docker icons sealed it for me - I think 3 is the way to go!

**Comment by kieraneglin** [comment]
Now that I'm finished grinding on the media center-related changes, I'd love to get the new logo and icon in place!

Would it be possible to get the assets of the 3 spoke design in the following formats:

- Coloured logo + white wordmark for in-app
- Coloured logo + teal wordmark for the README (since it needs to work with both light and dark backgrounds)
- Standalone icon for favicon, Unraid logo, etc

---

Once again, thank you SO much for all your hard work here. Design is not a skill of mine and your skills + input has been greatly appreciated

**Comment by hernandito** [comment]
Hi... files attached. I am sending full resolution... let me know if you want me to do them lower resolution. I am attaching two versions for the README... 

It is my pleasure to help. I am a little OCD when it comes to the graphic UI of things. I want everything running on my server to look top notch. 

![FINAL Pinchflat Full logo-ALT](https://github.com/kieraneglin/pinchflat/assets/787317/1c608e5c-570a-43a1-9809-c91e948eaaa9)
![FINAL Pinchflat Full logo-Teal](https://github.com/kieraneglin/pinchflat/assets/787317/85444806-f7f0-4379-8571-16868c3115b2)
![FINAL - Favicon](https://github.com/kieraneglin/pinchflat/assets/787317/5eb891c1-46b5-4374-9cdc-3cfb696e4c2d)
![FINAL Pinchflat Logo](https://github.com/kieraneglin/pinchflat/assets/787317/14d76fcd-2a98-4591-b0d9-9e9d6048dbc4)
![FINAL Pinchflat Full logo](https://github.com/kieraneglin/pinchflat/assets/787317/88cef7e7-4e68-4398-b86e-089bcb8a5a9c)

[Finals.zip](https://github.com/kieraneglin/pinchflat/files/14667161/Finals.zip)

**Comment by kieraneglin** [comment]
Perfect! I've put these together in PR #100. I left a comment with some screenshots - please let me know if you'd like to see anything changed before I merge!

One of the next things I'm going to focus on is improving documentation (and cleanup the README). After that, I'm going to likely move the app from `alpha` into an open `beta`!

**Comment by hernandito** [comment]
Looks great! Merge away…. I have to play w/ Pinchflat again to see how it now sets up the downloaded content.

Congrats and thank you for Pinchflat!

**Comment by kieraneglin** [comment]
Will do shortly!

There have been a lot of changes since you opened those initial issues. I recommend making a new media profile using the Media Center preset! I haven't tried it at all on Kodi, but I've been using it on Plex for a few days now with good results
