### ISSUE TITLE
Request: Add media cap for media profile

### ISSUE THREAD

**Issue by Cydget** [kieraneglin/pinchflat#81]
Please consider adding an option to only download the last N videos from a channel/media source url.  There are some channels I would like to add, but they have way too many older videos that I do not care to download.

below is how I did this manually with yt-dlp. It works with channels or playlists
--playlist-end TOTALCOUNT

Other nice to have functionality:
- Selectable date range
- max-filesize

**Comment by Cydget** [comment]
Even just having a field to enter yt-dlp arguments would be enough

**Comment by kieraneglin** [comment]
Fair enough! There is an option for a Source to only download media from after a certain date (`Download Cutoff Date`). Does that help at all?

I have plans for adding some kind of advanced mode where you can tag on custom `yt-dlp` arguments, but there are other things I'll have to get to first. That said, you're not the first person to ask for this so maybe I'll re-evaluate the priority of that feature!

**Comment by kieraneglin** [comment]
Closing since I haven't heard back on whether the `Download Cutoff Date` feature is sufficient 🤙
