### ISSUE TITLE
Editing a source

### ISSUE THREAD

**Issue by dayofdoom** [kieraneglin/pinchflat#92]
On Sources main page, clicking the source could enter into view mode, instead of having the view button at the end of the row. Once inside Source view mode, edit source button feels natural. 

#enhancement
#feature request

**Comment by kieraneglin** [comment]
Thanks for bringing this up! I've made it so you can click the titles of a source/media profile to view it as well as the icons at the end of the row

**Comment by dayofdoom** [comment]
Change looks great, thank you.
