### ISSUE TITLE
Plex Media Center Server integration

### ISSUE THREAD

**Issue by dayofdoom** [kieraneglin/pinchflat#93]
Plex Media Center Server integration similar to Radarr/Sonarr where once integrated, new downloaded files trigger a refresh for Plex
#enhancement

**Comment by kieraneglin** [comment]
Hey there! Thanks for bringing a few issues to my attention (:

With regards to Media center integration, I don't think this app needs to take any explicit action. As long as you are downloading to a folder that Plex is setup to watch, any new content you download should automatically get picked up. The *arrs work the same way and I don't have any explicit plex integration in, say, Sonarr. 

I recently released some default presets for media profiles and one of them optimizes for media center apps like Plex. Using that and making sure Plex is configured to watch that directory should be all you need to do! Also, I'm currently working to pull in banner art and stuff like that for sources to improve the way imported media looks in Plex. So there is some work to be done, but the basic import functionality should be ready to go. 

Let me know if this works for you!

**Comment by dayofdoom** [comment]
Thanks!

**Comment by kieraneglin** [comment]
Thanks for bringing that up! I didn't know that was possible. I started poking around in this feature and saw t[his official recommendation](https://wiki.servarr.com/sonarr/supported#plexserver):

> This is rarely needed and is only required if Plex is unable to watch the file system for changes.
>
> In the handful of situations where Plex is unable to watch the file system using ionotify - such as certain types of remote mounts and a handful of older network mounts - it is suggested to use the app plexautoscan rather than the Plex connection

Going off their guidance (and the personal experience that I've _never_ had updates be anything but instantaneous), I'm not going to add this as a planned feature for now. That said, I _am_ planning a feature to allow running arbitrary scripts post-download (including some default scripts for common use cases) which could be used to solve this issue!
