### ISSUE TITLE
How do I delete a source?

### ISSUE THREAD

**Issue by BillDStrong** [kieraneglin/pinchflat#94]
So, I give. 

Have I missed it?

**Comment by kieraneglin** [comment]
Click on the eye icon to view a source, then scroll down to the bottom 🤙🏻

**Comment by BillDStrong** [comment]
All right, I found it. Thanks.

So, I have suggestions. 

There are 2 more logical places you may want to delete a source. 
On the source page.

On the edit page, next to the save changes button. 

These are the places I looked, the first being an overall view that might eventually allow one to delete multiple sources at once, the second because it makes sense on a page that allows you to edit to allow the final edit.

I think I looked at the view page but didn't pay attention to the buttons down below.
